### ISSUE TITLE
Enhance chrome global media contols integration

### ISSUE THREAD

**Issue by Igorgro** [owncloud/music#1009]
Requesting improvement of chrome global media controls integration. This screenshot demostrates how this feature works with this musc app (first row) an the navidrome app (second row):

![screenshot](https://user-images.githubusercontent.com/22894169/189502737-ecb0b1b7-fa5c-484b-b3b7-4d7850dfc992.png)

Both meda files contains all required ID3 metadata and an album art

**Comment by paulijar** [comment]
It is not only about the media control popup shown in the screenshot but the media control integration in general is a bit flaky on Chrome. This includes e.g. the media control using the skip next/previous buttons on the keyboard. So basically it is supposed to work and sometimes it does work flawlessly, but then after hitting the reload button on Chrome, it often stops working. And after restarting Chrome, it usually works again. There are no issues like this on Firefox.

I suspect that the media control implementation of Chrome is buggy. It may have started with some recent update of Chrome as I have only noticed this during and after this summer. I have seen problems like this also on the sample https://googlechrome.github.io/samples/media-session/audio.html and on Youtube, alhtough for some reason, they are more common on the Music app.

I haven't figured out any clear root cause for this or anything which could be done differently on the Music app. But if anyone has any ideas, I'm all ears.

**Comment by paulijar** [comment]
I believe that Google has fixed Chrome at some point during the past year. I can no longer see this problem on the up-to-date Chrome version 121. The media control integration along with the popup controls work flawlessly even after multiple song changes and page reloads. No related changes have been made on the Music app.
