### ISSUE TITLE
Edge case with obscure artist name

### ISSUE THREAD

**Issue by StratusFearMe21** [owncloud/music#1021]
![image](https://user-images.githubusercontent.com/57533634/196314650-064a0915-1517-45d9-ae31-4957b8c3ca60.png)

So, what appears to has happened is, the sorting in the UI recognizes this artist (𝙼 𝚄 𝚂 𝙲 𝙰 𝚈 親 愛 な る) as being sorted under `M`, but the letter selector on the right side recognizes it as a `...` This causes it to skip over all the letters after L, making them un-navigable with the letter selector

**Comment by paulijar** [comment]
This problem happens because that artist name begins with a very special variant of the letter M, precisely this one: https://www.compart.com/en/unicode/U+1D67C. This is very special because it resides outside of the Unicode basic multilingual plane (BMP), i.e. the code point is more than U+FFFF. Such characters are represented with surrogate pairs in javascript and the logic of the alphabet navigation of the Music app breaks down on the surrogate pairs.

The good news is that I think I found a simple fix for this. I just need to test it a bit more.

**Comment by paulijar** [comment]
This is now fixed in Music v1.7.0.
