### ISSUE TITLE
[Bug] Some specific Music results in the Player stopping

### ISSUE THREAD

**Issue by DarkSide1305** [owncloud/music#1042]
The FLAC Album of A Link to the Past Enhanced Soundtrack (https://www.youtube.com/watch?v=I_jMOfoflMY - FLAC Download Link is in the description) has some sort of formatting to it that the Player doesnt like, it plays it for a split second before it stops. foobar2000, Pulsar (on Android) all dont have an issue with it, though I did have the Sonos Player at my work place that also doesnt play these files.

**Comment by paulijar** [comment]
Do you have this problem on all the files of that album? Because I tested a few of them and those played fine on Music app using Firefox, Chrome, or Edge. Moreover, they played fine even on the ancient Chromium version 55, which doesn't have the built-in FLAC decoder and it has to use the javascript-based fallback solution.

**Comment by DarkSide1305** [comment]
Huh, thats curious... on my Phone it works fine but on my Desktop it doesnt, im running an updated Firefox on Windows 10 though...

**Comment by paulijar** [comment]
I'm running Windows 10, too, and my Firefox is of the latest version 108.0.2 (64-bit). The tracks I tested were 0, 1, 20, and 33.

**Comment by DarkSide1305** [comment]
Ill get back to you tomorrow to tell you my exact Versions. Thats weird though, not working for me. Are you on Nextcloud 25?

**Comment by DarkSide1305** [comment]
Alright, im on Windows 10 (close to newest version) and Firefox 108.0.2 64-Bit too... thats really bizarre... I'll give deleting the songs and reuploading them a try, maybe something got corrupted at some point?

**Comment by DarkSide1305** [comment]
Okay now everything the same, JUST switched to Chrome and now it works...? I am really confused whats wrong with my Firefox that would cause this...

**Comment by paulijar** [comment]
Yeah, weird stuff. One thing to test is what happens when you take Nextcloud and the Music app off the loop: Download the file to your PC and then from the file explorer, select 'Open with' > 'Firefox' for the file. If the file still doesn't play then it proves it's all about Firefox and there's nothing which Music or Nextcloud could do to help. On the other hand, if it does play locally on Firefox, then we know that it also matter how Nextcloud and Music serve the file.

**Comment by DarkSide1305** [comment]
So it IS my Firefox, somehow... thats even more bizarre. It plays for 0.1 seconds, but then stops, not continuing, but technically it still plays. If I seek somewhere into the song it plays for like 0.1 seconds again and stops again...

**Comment by paulijar** [comment]
Closing as out-of-scope of the Music app.
