### ISSUE TITLE
/appinfo/app.php is deprecated

### ISSUE THREAD

**Issue by samps** [owncloud/music#1043]
Lately, my Nextcloud log has been flooded with a message saying:

/appinfo/app.php is deprecated, use \OCP\AppFramework\Bootstrap\IBootstrap on the application class instead. 

There's one such message every second. 
Is this a known issue and is there something I can do to fix it?

Nextclod is v25.0.3 running on Ubuntu 22.04LTS with Nginx and PostgreSQL

**Comment by paulijar** [comment]
This is a duplicate to https://github.com/owncloud/music/issues/907.

One thing to notice is that those messages are logged only on the debug level (0). In your normal daily use, you shouldn't have the logging level set as 'debug' since that will invariably make your log file grow very rapidly. Even without these deprecation notifications, there's still a lot of logging happening on this level.

**Comment by paulijar** [comment]
This issue is now finally solved in Music v2.0.0.
