### ISSUE TITLE
id3 tag change won't update

### ISSUE THREAD

**Issue by tigermick** [owncloud/music#1067]
Hi,
All work fine in music nextcloud app and thank you for that.
But I have a little problem ... I have scan all music on my serveur and if i change "genre" id3 tag in a music, I always find this last one in the same old "genre" section.
Is it possible to update id3tag of my music library please ?

**Comment by paulijar** [comment]
The Music app is supposed to update the data of the scanned files whenever those files change. But there's a gotcha: Nextcloud has to first detect those changes in order to notify the Music app. Now, if you for example modify the files directly in your server's file system, then Nextcloud doesn't know about those changes. But if, instead, you modify the file on a client computer and then re-upload the modified file or let the Nextcloud client sync the modified file to the server, then those changes should be detected by Nextcloud and it should trigger the Music app to rescan those files automatically.

Now, if you have modified your files so that Nextcloud doesn't know about it, you can still save the day by using the `occ` utility from the command line. You will need to use two separate commands:
- `occ files:scan` will update the internal bookkeeping of Nextcloud to be in sync with the Linux filesystem. Give it the argument `--help` to learn more about the options.
- `occ music:scan` with the option `--rescan-modified` will rescan those files which have got their "modified" timestamp upated in the bookkeeping of Nextcloud since the time when Music has scanned those files

**Comment by tigermick** [comment]
@paulijar thank you very much !
your solution works fine !
