### ISSUE TITLE
How to add missing album art?

### ISSUE THREAD

**Issue by emelbardis** [owncloud/music#1075]
Not really an issue of this app but I'm wondering the best way to manually (or automatically) add cover art to my files.

Thanks - this is such a great app and the Subsonic support is great!

**Comment by paulijar** [comment]
If your library is organized so that you have one folder per album, then you can just upload the cover image in any supported format (like jpg, png) to that folder and Music will pick it up and use it as an album cover. The canonical way is to call that file cover.jpg (or .png) but that doesn't really matter in case there is just one image file in the folder.

Your other alternative is to embed the cover art to the metadata tags of one or more tracks of the album. There's a wide variety of PC software able to do this; personally I have been using [Mp3tag](https://www.mp3tag.de/en/) to do this en-masse.
