### ISSUE TITLE
not playable files

### ISSUE THREAD

**Issue by ufgum** [owncloud/music#1076]
I have some flac files, that can not played by the music APP. Is there a way to debug this?

[Here is an example file](https://cloud.inhouse.us/s/Md5CgwkRYiT2X84)

**Comment by paulijar** [comment]
I tested your sample file. For me, it failed to play on Firefox but played fine on Chrome and Edge (all on Win 10). We primarily play files using the built-in decoders of the browsers which is why the mileage varies depending on the browser. We also have a fallback mechanism of attempting to play the file using the Aurora.js library in case the primary method fails, but on this sample file, also that fails.

Looking at the browser console on Firefox, the built-in decoder gives the error message "Error Code: NS_ERROR_DOM_MEDIA_METADATA_ERR (0x806e0006)" and Aurora.js gives the error message "Error: Invalid ADTS header". My best guess is that your file is now somehow slightly corrupted, but it depends on the implementation details of the audio decoder if that matters or not.

**Comment by ufgum** [comment]
Thank you. I figured out now, that the song plays fine, if I remove the lyrics from this file. Seems to be a problem with the text encoding.

**Comment by paulijar** [comment]
It's rather weird if lyrics (or any other metadata) affects the playback of any file. However, as there's nothing which the Music app could do to improve the compatibility, I'm closing the issue now.
