### ISSUE TITLE
Cannot export playlist to a file

### ISSUE THREAD

**Issue by Madzo007** [owncloud/music#1092]
Hi guys, for the past 2-3 weeks, suddenly i cannot export my playlists to a file. 
When selecting the "export to file" option from the drop-down menu, the path selection window pops up, but then there is no "save" button to actually save the playlist to the selected folder. The only option is to create new folder.  Thanks.

![image](https://github.com/owncloud/music/assets/20379270/8b3d3f90-20ef-448d-b27e-534ce52a7eec)

**Comment by paulijar** [comment]
This is most likely the same issue as https://github.com/owncloud/music/issues/1091. So for some reason, the folder selection dialog doesn't now work correctly on the most recent versions of Nextcloud.

**Comment by paulijar** [comment]
It seems that this happens because Nextcloud has accidentally broken their API compatibility and it has been fixed here: https://github.com/nextcloud/server/pull/40557. Hence, the issue should be gone in the NC version 27.1.2, which is scheduled to be released on 2023-10-19. I may be able to release a Music-app-side workaround before that but this remains to be seen.

In the meantime, you may export playlists from the command line by using the `occ` command `music:playlist-export`.

Anyway, I'm closing this issue as a duplicate.
