### ISSUE TITLE
smart playlist: unstable sorting

### ISSUE THREAD

**Issue by paroj** [owncloud/music#1099]
## settings
list size: 100
Play history: often played
rest: blank

## result
each time, I click update a different playlist is returned. Not merely a different order, but with different elements. Can be verified by setting list size = 3.

## expectation
"often played" should be deterministic and thus result in the exact same playlist (+sorting) each time.

**Comment by paulijar** [comment]
This is intentional, as the point of the feature is to create somewhat random playlists. Note that the filter name is "often played" and not "most often played" :). What is considered "often", is open to interpretation.

The implemented logic is such that when you request 3 often played tacks, the server will create a pool of 12 most often played tracks and randomly select 3 of them. However, if 12 would be more than half of all the tracks, then the pool size will be half of the total number of tracks. That is, it's guaranteed that the returned songs are always among the more often played half.

So formally, if requested list size is `S` and total number of tracks matching the other filters is `T`, then the server will select at most `S` random tracks among the `min(S*4, T/2)` most often played tracks.

**Comment by paroj** [comment]
uh.. I did not expect this to happen given my experience with other "smart playlist" implementations.

Maybe add a "Randomize" toggle to the filters tab. This way the randomization is user-visible and one could opt-out if one is after deterministic results.

**Comment by paulijar** [comment]
Maybe so. So would you still expect to get the results in random order, even if "randomize" wouldn't be selected? And what about the artist and genre filters: if there were 100 matches to the selected genre filter and you selected list size of 50, would you except to get the same 50 songs each time?

**Comment by paroj** [comment]
if randomize is off, then I would expect deterministic results, yes.

In your example with the "artist" filter, I would just sort the songs alphabetically. One could override that by selecting a "Play history" setting explicitly.

**Comment by paulijar** [comment]
The new Music app version 1.10.0 now has an optional "Strict" mode for the history filter of the smart list. In this mode, the filter selects only songs best matching the given rule, randomizing only the order.

**Comment by paroj** [comment]
why did you keep randomizing the order in "strict" mode? I really would like to have a list *in order* of date added or play count.

Anyway it works as expected if I set the length to 1 :)

**Comment by paulijar** [comment]
@parjo
Well, it was a judgment call. For me, creating randomized lists is *the* thing of this whole feature and I liked to keep the behavior of all the filters consistent. This view even started its life known as "Random" in the PR https://github.com/owncloud/music/pull/1061. Then the optional filters got added and the view was rebranded as "Smart list".

I'm also planning to introduce another feature "Advanced search" which is partially overlapping with the smart list feature. There, there would be even greater number of available search rules to combine and the default would be to return non-randomized results. Most of the heavy lifting is already done for such a feature because the back-end part has been implemented as part of the Ampache API. So it's now only lacking a web UI.

**Comment by paroj** [comment]
thanks for the heads-up
