### ISSUE TITLE
Which API do you recommend?

### ISSUE THREAD

**Issue by davipro34** [owncloud/music#1107]
Hello,
I'm working on cross-platform app development with Flutter.
I would like to develop a mobile application compatible with this Nextcloud Music application.

Indeed, after testing several applications like DSub, some user experience problems made me abandon them. Notably the impossibility of navigating by folder from the root of the Songs folder or the limitation of the number of sub-folders displayed. The search which only returns a sort starting from the artist name, and other limitations.
Please note, I have great respect for the authors of these applications and I admire the work accomplished.

I ask the question of knowing which API you advise me to use (Ampache, Subsonic, Shiva, REST?) in order to exempt myself from the limitations mentioned above in the development of my application?

Thank you in advance for your reasoned answers, I hope I can bring a little of my energy to your superb project.

**Comment by paulijar** [comment]
For a completely new client application, I would recommend the Ampache API. It's rather well designed and and offers a lot of possibilities. However, it has one shortcoming which may be critical to you: there's no support for browsing by the directory hierarchy.

On the other hand, the Subsonic API does enable the browsing by folder hierarchy and it has most of the same features as the Ampache API. But IMHO, the design of the API is rather horrible with all kinds of oddities. The bright side is that there is a rather large selection of Subsonic-compatible clients and servers available.

Shiva and proprietary REST APIs can't really be recommended for any external clients. They don't come with any authentication mechanisms, meaning that to use the API, there must be an active user session on Nextcloud. I don't even know, how that should be done on an external client app. I don't think that there has ever been any serious Shiva API clients which means also that this API is not very thoroughly tested. The proprietary REST API has been designed only for the needs of the web UI of the Music app. It probably doesn't include everything you need if your app doesn't have exactly the same kind of look-and-feel as our web UI. Also, the proprietary API is not documented and may change between the app versions.

**Comment by davipro34** [comment]
Thank you for the answer.
So I'm going to read up on the Subsonic API.
Do you know where to find a reliable and up-to-date source of documentation (in the version you implemented) for this API?
Is it fully implemented or are there any limitations I should be aware of?

**Comment by paulijar** [comment]
Yes, you found the correct documentation. The Music app implements most of the methods form the newest API version 1.16.1. The most important missing feature is that we don't support the token+salt authentication method. The reason is that although its purpose has been to improve the security, the bad design of the scheme makes it *less* secure than the traditional username + password authentication. Furthermore, the downsides of the plain password authentication can be easily mitigated by using HTTPS connection and HTTP POST instead of HTTP GET.

Other missing features are all the methods related to videos, shares, chat, or scanning. Also the method `jukeboxControl` is missing although I would like to implement it at some point (and it's not impossible that some of the other missing methods will be back-filled too, eventually).

This is the first time I hear of FlSub. That's no surprise as that seems to be a very new project. I didn't test the app, but on the github page it says that the app uses the token+salt authentication. If there is no option to enable the username+password authentication, then adding that needs to be your first task. Usually apps have a checkbox setting for this, but the client could change the authentication method also automatically, if the server responds to the token+salt authentication attempt with the error code 41. The original Subsonic server can't use the token+salt authentication when LDAP is being used and gives this error code in that situation. Nextcloud Music, on the other hand, responds with this error code to any attempt to use token+salt, regardless of LDAP (i.e. we have kind of extended the meaning of this error code).
![image](https://github.com/owncloud/music/assets/8565946/7f17abf3-9d22-45ea-a45b-a6decb26ee25)

**Comment by davipro34** [comment]
Thank you for the clarification on authentication.
I will continue to explore the FlSub code.
This looks interesting. The goal is to understand the code well.
This would save me from reinventing the wheel.
I will let you know if I have any interesting progress.
Thanks again.

**Comment by paulijar** [comment]
I believe there's no reason to keep this issue open any longer.
