### ISSUE TITLE
Error playing URL - on Android devices

### ISSUE THREAD

**Issue by pidlug** [owncloud/music#1127]
I have such a stream URL: http://mp3.polskieradio.pl:8904/;

It works fine on desktop client, but not on any Android clients gives "Error playing URL".
I'm not sure but it probably started after upgrade to Nextcloud v28.

It seems not the security "http in external sites" problem, because I have other http:// streams which work fine.

Music v1.10.0 on Docker Nextcloud:latest

**Comment by paulijar** [comment]
You mean you can play the stream using the browser and Music app web interface on PC but not on Android? That's weird, because for me, it doesn't play on any PC web browser. It does play, though, using the Subsonic API and the DSub client on Android.

I believe that this is because of how that stream URL behaves. When we load the URL http://mp3.polskieradio.pl:8904/ in the browser for playing, the same thing happens as when you click the link from here: The info page of the stream is loaded instead of the stream itself. This is apparently based on the User-Agent string sent by the browser to the stream server. This string cannot be spoofed on the modern browsers, so playing this stream on the web browser would require the feature https://github.com/owncloud/music/issues/1035.

**Comment by pidlug** [comment]
I found a workaround. On desktop I have Firefox, so I installed it on Android, and it works. So it is a browser thing.
It was not working in Mulch (based on Chromium).

I guess it can be closed?

**Comment by paulijar** [comment]
I still don't understand, how this can play without issues for you on any browser. Because for me, it doesn't play on Firefox either on Windows or on Android.

**Comment by pidlug** [comment]
The semicolon at the end is part of this crazy url ;-)
[http://mp3.polskieradio.pl:8904/;](http://mp3.polskieradio.pl:8904/;)

**Comment by paulijar** [comment]
Oh, that explains it then. I totally didn't see that one coming. With the semicolon added, it does work for me on Firefox and Chrome on Windows. Maybe then some browsers are as uncapable to understand the trailing semicolon as I was. :D

**Comment by pidlug** [comment]
I think it is not about the semicolon. I have other stream which behaves same way: http://audio.radiownet.pl:8000/stream
It plays perfectly in Firefox, by mpv etc. but not when in Chromium or other browsers based on Chromium.

**Comment by paulijar** [comment]
Okay. Somewhat interestingly, both [http://mp3.polskieradio.pl:8904/;](http://mp3.polskieradio.pl:8904/;) and http://audio.radiownet.pl:8000/stream play perfectly on the Music app using Chrome for Windows but only the latter of the two play if I click those links here on github. Other Chromium-based browsers might well have major differences to Chrome in the handling of audio files and streams. In the past (some years ago), the plain Chromium didn't even ship with any audio decoder for MP3 file type while Chrome did. This has changed since, but it might well be that the decoder used is not the same on these two.

Anyway, this is likely something which is out of the scope of the Music app: we can play only what the browser can play.

**Comment by pidlug** [comment]
Thanks. Closing then, as it is browser related...
