### ISSUE TITLE
No tracks listed in any of the synced albums

### ISSUE THREAD

**Issue by r3dpl4te** [owncloud/music#1131]
Hi, I originally reported this bug to Symfonium forum, a music player for e.g. subsonic servers, as implemented in Music App for Nextcloud.

**The main problem is that there are no tracks listed in any of the albums synced.**

If I click on the Artists name I can find the tracks available. Please see screenshots below.

I'll link to the forum if it's ok: https://support.symfonium.app/t/no-tracks-listed-in-any-of-the-synced-albums/3512/2
_Quote from @Tolriq :_
_"The logs are strange, the server returns the same data multiple times, they probably miss a sort leading to random result. "_

In **compatibility mode it works** like a charme, but for bigger databases I guess it could be lead into problems with no fast syncing.

----

**Information:**
* Subsonic API 1.10.0 Music App
* Nextcloud 28.0.2 Stable
* Meta data scanning enabled on both server and client or simply folder structure for some files listed im a simple folder
* No filter (at least not that I know)
* If you need any logs, tell me. I couldn't find any in the nextcloud apps/music folder.

* Id3 tags are/should be properly added or original added by e.g. audible. I checked them with different tag editors.
* And there is no difference in audio format. Reported behavior counts for mp3 and mb4 in this case.

----

Below screenshots
![image](https://github.com/owncloud/music/assets/96894071/8b0a53a4-9405-450e-bd7e-c2abe9f1c844)

![image](https://github.com/owncloud/music/assets/96894071/9bb518aa-0351-4312-bace-0fb01ef203ea)

Thank you very much
If you need anything more, just let me know. Besides that it works just great♥️
Kind regards
Wood

**Comment by paulijar** [comment]
We were discussing this issue [elsewhere](https://github.com/opensubsonic/open-subsonic-api/pull/84) with @Tolriq. If I understood it correctly, the root cause for this is because Nextcloud Music uses the musicFolderId argument in a way which is not strictly wrong but maybe a bit surprising and untypical, and Symfonium wasn't prepared for this. I believe that @Tolriq was planning to make a change on the Symfonium client and this shouldn't need changes on Nextcloud Music.

**Comment by Tolriq** [comment]
Version 9.0 have a workaround yes, and the issue is not much the values but the fact that there's 2 identical folders that returns the same data.
Since you are OS compatible and return the server type it's possible to detect and workaround so if no other apps did complain I guess there's nothing to change (My workaround is based on your comment that if you properly support folders one day you'll use positive values and no duplicates)

**Comment by paulijar** [comment]
Apparently Symfonium v9.0 is already released so could you give it a try @r3dpl4te?

**Comment by r3dpl4te** [comment]
Hi! I could indeed and run through the changelogs. Thank you very much @all, looks like the workaorund works 👍 :)

**Comment by paulijar** [comment]
Great, thanks for the verification!
