### ISSUE TITLE
Errors in the Nextcloud log when using the Subsonic XML API on NC28

### ISSUE THREAD

**Issue by Anvil5465** [owncloud/music#1142]
I get thousands of error messages per week in the log when using the Amperfy client.

See https://github.com/BLeeEZ/amperfy/issues/233#issue-2204058736

**Comment by paulijar** [comment]
Thanks for the report. This looks very similar to the issue https://github.com/owncloud/music/issues/1139. In that case, the client is making a slightly incorrect request, but I now tested and it seems to be irrelevant for the case. For me, this seems to happen on each Subsonic API call on NC28.0.2 but not on NC27.1.2. Apparently Nextcloud has changed something and I need to adapt.

**Comment by paulijar** [comment]
Further investigation revealed that this happened when calling the Subsonic XML API but not with the JSON API. The culprit seems to be the Nextcloud PR https://github.com/nextcloud/server/pull/38802 which changed the behavior of the `Response` base class. Should be fixed now and the fix will be released in Music 1.11.0 which is planned to ship before NC 29 is released.

**Comment by paulijar** [comment]
The fix is now released in Music v1.11.0.
