### ISSUE TITLE
hundreds of error messages in nextcloud.log

### ISSUE THREAD

**Issue by vasyugan** [owncloud/music#1159]
I'm using Nextcloud 29. Right now, checking the log I found hundreds of error messages of this type:

`{"reqId":"mG0ZRDkomHqyXfVrgfqu","level":3,"time":"2024-07-13T21:05:06+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"simplexml_load_string():  at /var/www/html/XXXX/apps/music/lib/Utility/PodcastService.php#184","userAgent":"--","version":"29.0.3.4","data":{"app":"PHP"},"id":"66938e2a20f9c"}
`
Unfortunately, I don't understand at all what the error is about. I also have two podcast related apps installed: Nextpod and gpodder sync. However, this error is thrown by the music app.

After unsubscribing from all podcast, I instead see this message over and over:
`
{"reqId":"ZpOShwdsWD3GDy57fAjdtgAADBI","level":3,"time":"2024-07-14T08:55:40+00:00","remoteAddr":"x.x.x.x","user":"XX","app":"PHP","method":"GET","url":"/XXXX/apps/music/api/album/4946/cover","message":"Trying to access array offset on value of type bool at /var/www/html/XXX/apps/music/lib/Utility/CoverHelper.php#318","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0","version":"29.0.3.4","data":{"app":"PHP"},"id":"669393df0ef3f"}`

**Comment by paulijar** [comment]
Thanks for the report. I believe that these two logged errors are two completely separate issues.

1. The first error is probably logged when one of your subscribed podcast channels returns somehow malformed data. It will get logged again each time the channel is checked for updates. The problem of the Music app is that it now lets a low-level error leak through to the log while it should handle those errors and show something more user-friendly in the log. However, I would assume that this kind of error row would be already today followed by the warning log line like "RSS feed for the channel NN was invalid". Have you possibly configured the logging level so that only errors (level 3) are visible?

2. Something is wrong with the cover art of the album 4946 in such a way that Music app is not handling it gracefully. You could check which album this is by navigating to the URL https://<your_server_address>/index.php/apps/music/#/album/4946.

**Comment by vasyugan** [comment]
Thanks! Unfortunately, after resetting my music collection, I cannot reproduce this issue. Will submit a fresh report, when it comes back. Closing for now.
