### ISSUE TITLE
Two different Albums merged to one Album

### ISSUE THREAD

**Issue by starmanager01** [owncloud/music#1169]
Hi, I have a little Issue. In a folder are 2 CDs with the same Name 

Folder Chicane 
-> Subfolder The greatest Misses 1234
----> 01 Title name 
-> Subfolder The greatest Misses 1235
----> 01 Title name (extended) 
In the Album view and in Subsonic it shows me 1 Album with every title double. 
In the Folder view I can see both Albums. 
Is there any chance to fix a problem like this? 
Title Names are same in both folders but some of them are exended versions. 

Thanks a lot for this great music tool

**Comment by paulijar** [comment]
In case your songs have the `album` metadata tag set, that is used to identify the album instead of the directory name. So presumably, your both albums have now the same content "Title name" in their `album` tag. You should set it as "Title name (extended)" (or anything you like) for your second album.
