### ISSUE TITLE
unicode characters

### ISSUE THREAD

**Issue by hasafi** [owncloud/music#136]
Hi,

 some special charakters are wrong:

```
Príli lutoucký kun úpel dábe
```

should be 

```
Příliš žluťoučký kůň úpěl ďábelské ódy
```

Thank you

**Comment by ignatenkobrain** [comment]
any news here?

**Comment by 4Vach** [comment]
Problem in mp3 tag version 1.1 Use v2 tags.
Convert tag in Linux. 
convert tags to version 2: "id3v2 -C ./music/*.mp3"
delete tag 1.1 version: "id3v2 -s ./music/*.mp3"
tag Utf-8 v2 work Ok :)

**Comment by paulijar** [comment]
I believe that these problems (or at least some of the similar issues) might have got fixed to the latest Music app releases with the update of the GetID3 library.

The root of these problems is that ID3v1 is supposed to contain only data encoded with ISO Latin 1 character set. ID3v2 tags, on the other hand, may contain data encoded as UTF-8 or any other specified character set. However, it's quite common that when metadata contains characters not representable in Latin 1, the metadata is written also to ID3v1 tags using some other encoding (which is against the specification). Another app cannot read back these tags reliably since the used encoding is unknown.

When a file contain both ID3v1 and ID3v2 tags, the GetID3 library tries to deduct which one contains more complete data and returns that. Now, this may lead to the incorrectly decoded v1 data being selected instead of the valid v2 data. But I think that GetID3 has made some improvements on this reconciling logic and the incorrect data is maybe not used so easily in recent versions. At least this didn't happen on my tests files created with Foobar2000 so that both v1 and v2 tags contained Czech on Arabic characters.

@hasafi @wtayyeb @ignatenkobrain Would you care to retest this old issue with Music app v0.4.3?

**Comment by paulijar** [comment]
As there has been no replies, I assume this issue is solved and can be closed.
