### ISSUE TITLE
MPEG-4 Audio support

### ISSUE THREAD

**Issue by jbtbnl** [owncloud/music#147]
Some music albums are distributed as MPEG-4 Audio (m4a). Any change the music app could support this?

**Comment by stefxh** [comment]
m4a works using chrome when you just RENAME the file from .m4a to .ogg. Because the music plugin uses SoundManager2 for files with ogg extesnion which utilizes the browser's built-in codec ([link to mozzila compability] (https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats#Browser_compatibility)).
It shouldn't be a big issu to implement the same behavoiur for m4a as for ogg.

**Comment by mmattel** [comment]
Is there any update on supporting m4a files natively without the suggestion of renaming?
Renaming a big music library is not an option as this breaks eg iTunes....

**Comment by benediktg** [comment]
I did create a shell function as a workaround for this:

```bash
mv-extension () 
{
        if (( $# != 2 )); then
                return 1
        fi
        for i in *.$1; do
                mv $i "${i%%.$1}.$2"
        done
}
```
So I can do

```bash
cd /path/to/owncloud/music/directory
mv-extension m4a ogg
sudo -u www-data php /var/www/owncloud/occ files:scan --all
sudo -u www-data php /var/www/owncloud/occ music:scan --all
```

Not the nicest way but it works for me.

**Comment by MorrisJobke** [comment]
> This function just renames all files in the current directory with the extension given by the first argument to a file with one given by the second argument. So I can do

Why then not send the correct mimetypes and not deal with renames ;) The browser seems to simply not properly recognize this.

**Comment by mmattel** [comment]
Try to summarize the issue:

- We currently do not scan files having a extension of .m4a (mp3, ogg and others are scanned). Therefore we do not have any m4a files in the database, even they are present in the filesystem
- The used plugin: SoundManager2 is capable playing m4a files
- Renaming m4a files to ogg files would make them playable, but is a no-go.
But it also shows that the environment would be able to pay them.
- Code needs to be adopted to: identify and scan m4a files, handle the correct mimetype for this media file

Something missing?

**Comment by MorrisJobke** [comment]
> We currently do not scan files having a extension of .m4a (mp3, ogg and others are scanned). Therefore we do not have any m4a files in the database, even they are present in the filesystem

This needs to be done in core then. :(

**Comment by mmattel** [comment]
**If I query my SQL database with:**

``SELECT * FROM `oc_filecache` WHERE `name`LIKE  "%mp3"`` I get +5000 entries
``SELECT * FROM `oc_filecache` WHERE `name`LIKE  "%m4a"`` I get +7000 entries

``SELECT * FROM `oc_music_tracks` WHERE `title` like "%mp3"`` I get +1500 entries
``SELECT * FROM `oc_music_tracks` WHERE `title` like "%m4a"`` 0 entries,

There are in total +12000 music files...

So the scanner of core does scan all possible files
But the Music App does not identify all of them

**Here is another info, maybe helpful:**

According to mp3tag:
The mp3 files have as tag: ID3v2.2 (ID3v2.2) or ID3v2.3 (ID3v1 ID3v2.3)
The mp4 files have as tag: MP4 (MP4)

**Comment by mmattel** [comment]
https://github.com/owncloud/core/pull/24006

**Comment by mmattel** [comment]
Now the good newswith the above PR referenced:

``SELECT * FROM `oc_filecache` WHERE `title` like "%m4a"`` I get +7000 entries
``SELECT * FROM `oc_music_tracks` WHERE `title` like "%m4a"`` I get +7000 entries

**Comment by mmattel** [comment]
Now to check why the different mp3 tags create a subset of playable tracks

**Comment by mmattel** [comment]
Just to ask,

1. Would it be possible to replace getid3 in music by using ID3Parser from core https://github.com/owncloud/3rdparty/pull/267 ?
2. Which version is ID3Parser based on, because of a iTunes fix, see comment above 
3. Are there all audio related files scannable with ID3Parser like in getid3 or only a subset?

cc @LukasReschke

**Comment by mmattel** [comment]
Info, I just tested ID3Parser against a mp3 and m4a file with:

````
<?php
require_once('./lib/base.php');

$analyzer = new \ID3Parser\ID3Parser();
$tags = $analyzer->analyze('/mnt/02.m4a');

print_r($tags);
?>
````

And I got in both test a valid response.
The question with the three items above stay valid, because the test just highlighted that it is possible but we need clearance to proceed.

**Comment by LukasReschke** [comment]
> Would it be possible to replace getid3 in music by using ID3Parser from core owncloud/3rdparty#267 ?

If only the ID3 parsing functions are required by the music app. Yes. 

> Which version is ID3Parser based on, because of a recent iTunes fix in getid3, see comment above

1.9.12

> Are there all audio related files scannable with ID3Parser like in getid3 or only a subset?

I only tested it with MP3 files what is required in core. All other stuff would require manual testing.

I'd recommend to just update the shipped getID3 version in the music app :)

**Comment by paulijar** [comment]
After the core PR mentioned above (https://github.com/owncloud/music/issues/147#issuecomment-210044716) got merged, the m4a and m4b files have been included in the music library. However, playing them from the web UI has not been possible because of a hard-coded MIME type check on the Music app front-end.

The front-end support was now added with commit b8c3d4a43c17. The playback of m4a files works at least on Chrome, Firefox, and Edge. Playback of m4b works on Chrome and Firefox.
