### ISSUE TITLE
.opus support

### ISSUE THREAD

**Issue by Epicanis** [owncloud/music#161]
.opus (opus[1] codec in ogg containers) is becoming a relatively popular new format due to the high quality, versatility, and now wide availability (firefox has supported it for almost 2 years. Chrom(e|ium) has had "off by default" support for a year or so, and has recently made it available by default as of early 2014. Rockbox, vlc, and numerous other media players also support it now).

It appears from looking at the code[2] that only ".mp3" and ".ogg" files are recognized as audio media currently. Could this be updated? (.opus music files for testing available on request).

[1] http://opus-codec.org
[2] https://github.com/owncloud/music/blob/master/utility/scanner.php (line 132 as of 2014-03-12)

**Comment by Epicanis** [comment]
It appears getID3 1.9.9 (Just released Dec 18th) adds support for .opus[1], which I'm guessing was the major impediment to this besides (I'm assuming) adding ".opus" to the list of recognized file types.

[1] http://www.getid3.org/source/changelog.txt

**Comment by BigButt** [comment]
@Epicanis
So all it needs is an update?
Last update was back in September (version 0.3.4). Looking forward.

**Comment by MorrisJobke** [comment]
I try to get the updated getID3 in here. Thanks for the info.

**Comment by Epicanis** [comment]
As a disclaimer I should clarify that I really don't have much understanding of owncloud's code - I'm just looking mainly at the scanner.php code (and glancing at the rest) of the music app and it LOOKS like anything recognized as an "audio" mimetype (or "application/ogg") that either has a title tag recognizeable by getID3 OR is a ".ogg" or ".mp3" file should show up. I think.  Based on that assumption, and the assumption that whatever the mimetype is being detected by correctly recognizes .opus files as "audio/ogg" (or "audio/ogg; codecs='opus'"), and finally the assumption that .opus support in getID3 1.9.9 really works (haven't tested it yet) it LOOKS like an update to getID3 should get any .opus file with a "TITLE=" vorbiscomment to appear in the music app.

**Comment by muchbetterbig** [comment]
Since Opus is not compatible with most popular players and devices so far, it's absolutely impracticable, no matter directly play Opus files on Windows Media Player, Android, PS3, Xbox 360 and iTunes or sync Opus to iPhone, iPod, iPad via iTunes, or edit these Opus in iMovie and QuickTime.

Under the circumstances, the best solution is to convert Opus to MP3, WAV, WMA, OGG, FLAC, AAC and other more compatible audio formats in order to play or edit Opus in the above popular players and devices 

Step by step guide at http://www.idealshare.net/audio-converter/opus-converter.html

**Comment by BigButt** [comment]
I disagree. Such thinking kills all progress.
Opus is an open standard available for many platforms btw.
For instance VLC Player, Chrome and Firefox support opus.

Opus is the best choice for online streaming because quality and compression is superior especially on lower bit range.
I even want to encode for that purpose.

**Comment by pellaeon** [comment]
The actual problem is that I've been trying to build upstream Aurora.js / opus.js codec, without a working result. This problem is probably upstream, until I figure out a way to build working opus.js or upstream fixes that, we won't see opus support is ownCloud Music app.

**Comment by the-kyle** [comment]
My portable player running Rockbox supports the opus audio standard, and
I encode everything I have into that smaller and superior file format.
It would make perfect sense for OwnCloud's embedded music player to
support it as well, so that I can play my files on my phone and in my
browser without converting or re-converting them to non-free or larger
files.

**Comment by jgillich** [comment]
Is Opus still not supported? The README says otherwise, but it just hangs on scanning for me ("0 of 2350").

**Comment by paulijar** [comment]
@jgillich I don't know about the Opus support (have never tested), but the hanging scanning sounds like #538 which should be fixed in the next release of the Music app.

**Comment by jgillich** [comment]
Thanks, with that workaround scanning is working, and so is playing my Opus music! I think this can be closed, it probably was supported for a while.
