### ISSUE TITLE
Seeking in Chromium doesn't work

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/music#176]

**Comment by paulijar** [comment]
Supporting seeking with Chromium would require the seeking to work in Aurora.js and its plugins. Those don't seem to be very actively maintained so the hopes are not too high. Seeking works fine in Chrome, Firefox, and Edge since those browsers have the native codecs are do not need to use Aurora.js for playback.

**Comment by paulijar** [comment]
For the record, I retested seeking with the updated aurora.js + plugins included in Music 0.4.4, but this did not help: Like previously, seeking worked for some mp3 files but on others it caused playback to stop and it couldn't be resumed by any other means than changing to another song.

**Comment by paulijar** [comment]
Nowadays, some (all?) distributions of Chromium seem to include the audio codecs. Hence, SoundManager2 is used instead of Aurora.js and also the seeking works fine on these Chromium versions. I think this issue can now be closed.
