### ISSUE TITLE
Broken design in IE8

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/music#179]
![bildschirmfoto von 2014-03-24 16 57 31](https://f.cloud.github.com/assets/245432/2501560/85ad3a50-b36d-11e3-8b4d-81dd006196d9.png)

**Comment by jancborchardt** [comment]
I really wonder if it should be a requirement of community-developed 3rd-party apps to support IE8 (also see https://github.com/owncloud/music/issues/178).

I would argue strongly against it since support is ended and the amount of people using it doesn’t justify the amount of work needed to put into it. Sure: core, Files etc we need to support for IE8, but I wouldn’t make it a requirement for community-developed apps. cc @karlitschek
