### ISSUE TITLE
Ampache : bad characters in XML response

### ISSUE THREAD

**Issue by wzv** [owncloud/music#214]
Hi,
I'm testing v0.1.9.1-rc !

Steps to reproduce :
Add a song to your collection with an artist, album or song that contains a character like "éèêà" etc. 
For exemple : 
MariaDB [owncloud]> select title from oc_music_tracks;
+-----------------+
| title           |
+-----------------+
| Osez Joséphine  |
+-----------------+

Actual result :
Ampache xml response seems bad formatted because in my ampache client I've an exception like that "XmlPullParserException : unresolved & eacute;(position:Text@3:26)"
Nothing in owncloud logs.

Expected result :
Good Xml response

Thanks !

**Comment by paulijar** [comment]
I can't reproduce this old issue on recent Music app and ownCloud/Nextcloud versions. Artist named "Zen Café" shows up and plays fine via Ampache API on Tomahawk for Windows and on Power Ampache for Android. Maybe this has got fixed at some point or then the problem was in the client end in the first place.
