### ISSUE TITLE
[0.2]Scanning does not finish

### ISSUE THREAD

**Issue by hendrik-donner** [owncloud/music#223]
Hello,

Scanning never finishes and is hanging at "Scanning... 50/51". 
I only have 50 music files(mp3, flac and ogg).

Log:
Info    music   Rescan finished (50/51)     2014-05-03T10:36:19+00:00
Info    music   Rescan triggered    2014-05-03T10:36:19+00:00
Info    music   Rescan finished (50/51)     2014-05-03T10:36:19+00:00
Info    music   Rescan triggered    2014-05-03T10:36:19+00:00
Info    music   Rescan finished (50/51) 2014-05-03T10:36:18+00:00
Info    music   Rescan triggered    2014-05-03T10:36:18+00:00
Info    music   Rescan finished (50/51) 2014-05-03T10:36:18+00:00
Info    music   Rescan triggered    2014-05-03T10:36:18+00:00
... 

I tried deleting everything from the oc_music_\* and start over again, that does not help.
Any ideas?

**Comment by paulijar** [comment]
I think it's safe to close this issue after five years of inactivity. So many things have changed in the Music app scanning logic and in ownCloud core since the reporting, that the reported issue is probably no longer applicable. New bug should be raised if such issues can be seen on the latest versions.
