### ISSUE TITLE
Music player does not working well

### ISSUE THREAD

**Issue by sbh01** [owncloud/music#294]
When i click on any music filles i see new page with all music files from owncloud.
When i click there on for example @unknown album@ where about 15 songs, i see how player jump from one file to another and on 8 or 9 he start to play. So i think there is problems with playing other files.

**Comment by blizzz** [comment]
@sbh01 does the issue exist for you with current versions?

**Comment by paulijar** [comment]
There seems to be multiple issues mentioned in this report. I believe that at least #404 and #306 are behind the perceived problems. There might be also other problems as this was reported a long time and many Music app versions ago. The chances are good that the problems are no longer present in the latest app version 0.4.3. As there also hasn't been an answer from the reporter for two years, I think it's safe to close this issue.

**Comment by nikhilroy2** [comment]
I have the same problem, when I play the music the github server not play it but my vs code server working, what is issue, need to solve it , please help, 
github page which is problem, 
https://nikhilroy2.github.io/27-Days-Target-30-Project-Music-Player-with-Javascript/
please solve my problem,,

**Comment by paulijar** [comment]
@nikhilroy2 I'm pretty sure you don't have the same problem as the ones described here. This thread is about bugs in the ownCloud Music app 5 years ago, and you seem to have problems with your own javascript player project, which seems to have nothing to do with ownCloud or this app. Please note, that posting here causes email notifications to several people who are probably not interested about your problem.

But because I'm a nice guy, I give you a free tip: If you open the browser developer tools and press Play in your player, you can see the following message in the console: `HTTP load failed with status 404. Load of media resource https://nikhilroy2.github.io/songs/Tui_aka_aka_bose_keno_acho.mp3 failed.`. If you then try to navigate to https://nikhilroy2.github.io/songs/Tui_aka_aka_bose_keno_acho.mp3, you see that no such thing exists. So you are now trying to play something which is not there. If, instead, you would use URL https://nikhilroy2.github.io/27-Days-Target-30-Project-Music-Player-with-Javascript/songs/Tui_aka_aka_bose_keno_acho.mp3, then the target can be found.
