### ISSUE TITLE
Music collection in external storage not detected

### ISSUE THREAD

**Issue by keirlawson** [owncloud/music#301]
Using Owncloud 7.0.2 my music collection, mounted via external storage, is not displayed within the music player. The player does seem to scan the directories but apparently finds nothing. Files are mostly MP3.

**Comment by jleaders** [comment]
I'm having the exact same issue.

For example, If I have music on an external hard drive. I set the music up to 'mount' in OwnCloud to /Music/

I add /Music/ to the Music app's location.

I go to the music app, and it shows an error, "Nothing in here. Upload your music!"

**Comment by Xavtak** [comment]
I'm also having the same issue.
### Steps to reproduce
1. Fresh Owncloud install
2. Login as admin
3. Mount "local" external storage to folder "Music", make it available to a user (called "User" for example).
4. Install Music App and enable it.
5. Login as "User", go to Music app.
6. Ask for collection scan.
7. Enjoy listening to your music!

### Expected behaviour
After scanning for music files, the music app should list all available music.

### Actual behaviour
Scanning for musing files seems to work at first, since the progress bar indicates the correct number of total music files (around 3,000. mp3, ogg and flac mixed)
However, once scanning is done, collection remains empty: "Nothing in here. Upload your music!".
Call to https://<server>/owncloud/index.php/apps/music/api/collection just returns "[]"

Music files are listed in the File app. If I click on one, Music app opens:
URL: https://<server>/owncloud/index.php/apps/music/#/file/958
but still the same "Nothing in here..." message.
If I middle click on the file in File app, I can download it.

### Server configuration
**Operating system**: 
Ubuntu 14.04 (64 bits)

**Web server:** 
Apache2

**Database:** 
SQLite

**PHP version:** 
PHP 5.5

**ownCloud version:** 
8.0

**Updated from an older ownCloud or fresh install:** 
Fresh install

**List of activated apps:**
Activity 1.2.0
Bookmarks 0.4
Calendar 0.6.4
Contacts 0.3.0.18
Deleted Files 0.6.2
Documents 0.9.0
External Sites 1.2
External Storage Support 0.2.3
File Locking
First Run Wizard 1.1
Mail Template Editor 0.1
Music 0.3.5
PDF Viewer 0.7
Pictures 0.6.0
Provisioning API 0.2
Share Files 0.6.0
Text Editor 0.4
Updater 0.4
Video Viewer 0.1.3
owncloud SMS 1.4.1

**The content of config/config.php:**

```
(Will update later, no access to file system for now)
```

**Are you using external storage, if yes which one:** 
YES: local

**Are you using encryption:**
NO

**Are you using an external user-backend, if yes which one:**
NO

### Client configuration
**Browser:**
Tested on Firefox 21, 31, 35, 36

**Operating system:**
Tested on Windows XP, Windows 7, Ubuntu 14.04

### Logs
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
(Nothing relevant at levels Warning or higher)
```

#### Browser log
```
(Nothing relevant)
As stated above, https://<server>/owncloud/index.php/apps/music/api/collection just returns "[]"
```

**Comment by Xavtak** [comment]
Hi,
I've made some more testing.
It appears that in my case, and I cannot speak for keirlawson or jleaders, the problem may not be linked to external storage, although I use it.
If I set the collection root to a single artist's folder, instead of the whole collection, it works fine.
Here is a little experiment I've done, with browser network log enabled.

First, I choose the whole music collection.
* Go to user preferences, choose /Music/ as music path.
 * POST path query
  * -> Parameters: value="/Music/"
  * -> Returns {success: true}
* Go to Music app.
 * GET collection query
  * -> Parameters: None
  * -> Returns: Nothing
 * GET scan query
  * -> Parameters: dry=1
  * -> Returns: {0: {processed: 0, scanned: 0, **total: 0** } }
 * Displays: "Nothing in here..."
 * **Does not display: "Unscanned files" link**

Then I did the same on a single artist's folder:
* Go to user preferences, choose /Music/Adele/ as music path.
 * POST path query
  * -> Parameters: value="/Music/Adele"
  * -> Returns {success: true}
* Go to Music app.
 * GET collection query
  * -> Parameters: None
  * -> Returns: Nothing
 * GET scan query
  * -> Parameters: dry=1
  * -> Returns: {0: {processed: 0, scanned: 0, **total: 1** } }
 * Displays: "Nothing in here..."
 * **Displays: "Unscanned files" link**

I've also checked for ownCloud logs, but they are utterly empty regarding Music app.
Also, please note that the scan?dry=1 query runs very fast either way, even on the 3,000 song collection.

Let me know if there is any other test I may run...

**Comment by MorrisJobke** [comment]
Thanks for testing.

**Comment by paulijar** [comment]
@keirlawson @Xavtak @jleaders This issue is old but is it still valid with most recent Music app version (currently 0.5.4) and more recent ownCloud/Nextcloud version?

**Comment by paulijar** [comment]
With almost a month with no reply, I assume that this old issue is no longer valid.
