### ISSUE TITLE
Ampache auth failed (LDAP)

### ISSUE THREAD

**Issue by stanelie** [owncloud/music#330]
### Steps to reproduce
1. try to connect ampache client
2. see below for more details
   3.
### Expected behaviour

Ampache client should connect
### Actual behaviour

Ampache client does not connect
### Server configuration

Ubuntu 14.04

**Web server:**
Apache2
**Database:**
MySQL
**PHP version:**
 5.5.9-1ubuntu4.5
**ownCloud version:** (see ownCloud admin page)
7.0.4
**Updated from an older ownCloud or fresh install:**
updated
**List of activated apps:**
activity
bookmarks
calendar
contacts
deleted files
documents
embedded video stream
external storage support
first run wizard
full text search
ldap users and groups backend
pdf viewer
pictures
share files
text editor
updater
versions
music

**The content of config/config.php:**

```
Insert your config.php content here
(Without the database password and passwordsalt)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
### Client configuration

**Browser:**
viridian
**Operating system:**
debian
#### Web server error log

```
Insert your webserver log here
```
#### ownCloud log (data/owncloud.log)

```
Insert your ownCloud log here
```
#### Browser log

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

Hello.
The ampache authentication is failing on my owncloud 7.0.4 with music plugin 0.3.4. I use a mix of LDAP users and native users. The LDAP users always get Auth failed, the regular users are able to connect to Ampache.

In my users list, I noticed that the LDAP username field is populated with UUIDs. If I use the LDAP UUID as login name to Ampache, it works!

**Comment by sh1ny** [comment]
I can confirm, the same bug happening on OwnCloud 8 with music app checked out from git. Authenticating with username + generated token when using LDAP ( in my case FreeIPA ) fails, but when replacing the username with the ldap uniqueID ( something like "f60eea09-a62911e4-9da0ee3b-2a9892ff" ) it works. Is this LDAP configuration issue or music app issue ?

**Comment by MorrisJobke** [comment]
Let me test that with LDAP. THanks for the report

**Comment by stanelie** [comment]
I still have this issue with owncloud 8.0.4, music app 0.3.6.

**Comment by MorrisJobke** [comment]
> Authenticating with username + generated token when using LDAP ( in my case FreeIPA ) fails, but when replacing the username with the ldap uniqueID ( something like "f60eea09-a62911e4-9da0ee3b-2a9892ff" ) it works.

Mmmh. This is because LDAP works internally a bit different and accepts multiple usernames. Would it help, if the username to use is also shown in the ampache API key config?

**Comment by sezuan** [comment]
That would avoid some confusionn, but it's a PITA to enter UUIDs on devices where copy-and-past is difficult or impossible. It would be nice to be able to use the normal username.

**Comment by MorrisJobke** [comment]
> It would be nice to be able to use the normal username.

The problem then is, that I need to interact actively over private methods with the LDAP app (which will most likely break very often). @blizzz Do you have a nice idea how to resolve a login name via LDAP to an owncloud name?

**Comment by blizzz** [comment]
@MorrisJobke use the login filter to obtain a DN, use the mappings to get the ownlcoud name based on the DN. Since 8.1 there is a public method in LDAP's Access class "fetchUsersByLoginName" which does that for you and returns all user DNs matching  the login name. Pass the DN to dn2username() and it will return the owncloud username (or false). Instantiating Access is a little bit of PITA though, if you also pass a proper userManager (i.e. make a fake one). Don't forget to set the user mapper using setUserMapper().

**Comment by stanelie** [comment]
In the meantime, if the app was able to display the username it expects, it would make me and my users very happy. Also, an option to display the password in the config for later use, instead of having to generate one every time you reinstall JustPlayer or some other player would be nice...

**Comment by paulijar** [comment]
The user name needed for Ampache login has been visible after generating a new password since the release v0.9.1. Automatic mapping from LDAP login name to the corresponding internal user name (i.e. the UUID of the user) is not a viable option, at least for now, because there's no public API for this which would be available both on ownCloud and Nextcloud. Typing in the UUID may be a bit cumbersome, but on the other hand, even mobile browsers should nowadays support copy-paste. Hence, I think this solution is "good enough".

Displaying the password later on the settings page is not possible because, literally, the Music app does not know the password. The application stores only the hash of the password; the plain text version of the password is forever gone after the user closes the settings UI after generating a new password.
