### ISSUE TITLE
Next Button doesn't change the album

### ISSUE THREAD

**Issue by supportreq** [owncloud/music#350]
Currently the album is not automatically changed when pressed the next/previous button.

It should play all music in the storage and not just restricted to one album

**Comment by supportreq** [comment]
### Steps to reproduce
1. Open Music
2. Owncloud should have music files of different albums [each album has one music file]
3. Click on Play music
4. Click on the Next button

### Expected behaviour
Once the next button is pressed it should play the next song even if it is in a different album

### Actual behaviour
Once the next button is pressed [and in case there is no music in the same album] it stops playing..

### Server configuration
OwnCloud : 7 & 8

**Comment by MorrisJobke** [comment]
@supportreq Thanks for the report

**Comment by paulijar** [comment]
After commit a89210456, the app enqueues all the albums for playing when a track is clicked. Previously, the playback was restricted to one album in this case. When Shuffle is off, this means that playback continues from the next album once end of album is reached. When Shuffle is on, this means that the app shuffles among the whole library instead of shuffling only tracks of the single album.

The old behavior of playing/shuffling only one album can still be activated by clicking the album title or album cover picture.

**Comment by paulijar** [comment]
Version 0.9.0 with this feature is now released.
