### ISSUE TITLE
Continue playing after seek

### ISSUE THREAD

**Issue by pellaeon** [owncloud/music#400]
For seekable music formats like FLAC, when you click on the seek bar, music stops playing, and the controls are still in "playing" state (displaying the pause button).
If you click on the pause icon than click again on the play icon the music continues playing at the seek location.

I will try to fix this.

**Comment by paulijar** [comment]
I think that the described behavior is just one of the seeking bugs of the Aurora.js backend. Because of these bugs, seeking on aurora has been disabled for quite some time. After 72a893be649, Chrome and Firefox use SoundManager2 to play also FLAC files, meaning all the audio formats can now be seeked without issues. Closing.
