### ISSUE TITLE
Wrong encoding with russian symbols in metadata

### ISSUE THREAD

**Issue by rakshazi** [owncloud/music#410]
Hello!
I have songs with russian symbols in filenames and metadata, here is how they are displaying in OwnCloud Music app:
![](https://s3.amazonaws.com/upload.screenshot.co/7de9d05b1d)

Please, fix this!

OwnCloud 8.1.1, russian language, UTF-8 encoding.

**Comment by oddmean** [comment]
The same problem with OC 8.2.1 (Music v. 0.3.8).

**Comment by sprnza** [comment]
The same problem with OC 9.0.0 (Music v. 0.3.10)
`locale -a
C
en_US.utf8
POSIX
ru_RU.utf8
`

**Comment by paulijar** [comment]
I believe that updating the getID3 library to version 1.9.14 with 26c1d5d70f fixed this issue. I don't see the example of the wrong behavior in the opening post but when I tested this myself, I saw strings of question marks like "??????????" instead of the Cyrillic characters. After the library update, I saw Cyrillic characters being printed properly in the artist, album, and track name fields.

**Comment by sprnza** [comment]
Yep, works like a charm!
