### ISSUE TITLE
App management in ownCloud 8.1.1 is not showing latest app version

### ISSUE THREAD

**Issue by rakekniven** [owncloud/music#423]
On my ownCloud v8.1.1 I have music app installed in version 0.3.5.
Got this version kept from previous 8.0.x versions.
Today I saw music app in version 0.3.7 in app store and here on github as well.

Please adapt release information to show latest version in ownCloud's app administration.

**Comment by MorrisJobke** [comment]
I think you installed an old version :( The problem was, that back in time we need to have different appids for each owncloud version. Nowadays the appstore can handle apps, that work on multiple owncloud versions. I guess you need to use the proper version or change the ocsid in appinfo/info.xml to `164319`

This should then automatically update the entry in the DB, right @LukasReschke ?

**Comment by LukasReschke** [comment]
> This should then automatically update the entry in the DB, right @LukasReschke ?

Erm. No. :tada:

**Comment by LukasReschke** [comment]
See also https://github.com/owncloud/core/blob/bef8dd41714f5fd797166c6f47549e360919be31/lib/repair/updateoutdatedocsids.php :tada:

**Comment by MorrisJobke** [comment]
Ah okay. So you also have to update the table `oc_appconfig` with `appid = "music"` and `configkey = "ocsid"` to `configvalue = 164319`

**Comment by MorrisJobke** [comment]
Then the update should be shown.

**Comment by MorrisJobke** [comment]
Starting with 8.2 we will have a cli tool to update those values in the DB.

**Comment by rakekniven** [comment]
Did manual update in the meantime. 
Will see if it works on next release on music app.

btw. like the app. Thumbs up
