### ISSUE TITLE
Add music client Qt-app to owncloud repo

### ISSUE THREAD

**Issue by suratovvlad** [owncloud/music#466]
I and my friend developed [crossplaform application](https://github.com/van-ess0/qwnPlayer) (Qt-based) for listening music using API of this owncloud music app.
It works fine on main desktop platforms: Windows, Linux and OS X, and some mobile platforms - iOS, Android (4.4.x) and Sailfish OS. It will work on Android L and M and even on Windows Phone 8.x and Windows 10 Mobile if someone of Qt mainteners fixes [this bug (QTBUG-49237)](https://bugreports.qt.io/browse/QTBUG-49237) or if we use QtVLC (or just libvlc) for playback on devices.
So, we want to add our application to owncloud repo, is it real?

P.S. Excuse me, @DeepDiver1975, I've got advice from owncloud-dev IRC users to create issue and mention you here.
![image](https://cloud.githubusercontent.com/assets/3812290/12875946/4de7a366-ce06-11e5-992f-6bba956d03bc.png)

**Comment by paulijar** [comment]
I don't know why no-one has reacted to this request when it was posted, but I don't think this belongs under the Music app. I don't know what would be the correct place, though. Also, it seems to me that the development of the said Qt-app has been abandoned since the latest commit to the repository is over 18 months old and has been submitted just 11 days after opening this issue.

I also gave a try for the latest binary release of this Qt app on Windows 10 but I could not make it connect my ownCloud instance. Maybe it can't handle https? There were no error messages on the client or server.

Closing as off-topic and obsolete.
