### ISSUE TITLE
  [OCA\Music\AppFramework\BusinessLayer\BusinessLayerException]   More than one result

### ISSUE THREAD

**Issue by russellharrower** [owncloud/music#480]
I am unsure why I am getting the following

```
  [OCA\Music\AppFramework\BusinessLayer\BusinessLayerException]
  More than one result

```

**Comment by JetUni** [comment]
I am getting the same error when scanning my music files via the shell. I run sudo -u www-data ./occ music:scan -v username and I get this:

```
[OCA\Music\AppFramework\BusinessLayer\BusinessLayerException]
  More than one result


Exception trace:
 () at /var/www/owncloud/apps/music/businesslayer/albumbusinesslayer.php:103
 OCA\Music\BusinessLayer\AlbumBusinessLayer->addAlbumIfNotExist() at /var/www/owncloud/apps/music/utility/scanner.php:268
 OCA\Music\Utility\Scanner->update() at /var/www/owncloud/apps/music/utility/scanner.php:399
 OCA\Music\Utility\Scanner->rescan() at /var/www/owncloud/apps/music/command/scan.php:93
 OCA\Music\Command\Scan->execute() at /var/www/owncloud/3rdparty/symfony/console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at /var/www/owncloud/3rdparty/symfony/console/Application.php:840
 Symfony\Component\Console\Application->doRunCommand() at /var/www/owncloud/3rdparty/symfony/console/Application.php:192
 Symfony\Component\Console\Application->doRun() at /var/www/owncloud/3rdparty/symfony/console/Application.php:123
 Symfony\Component\Console\Application->run() at /var/www/owncloud/lib/private/console/application.php:145
 OC\Console\Application->run() at /var/www/owncloud/console.php:88
 require_once() at /var/www/owncloud/occ:11

music:scan [--all] [--debug] [--] [<user_id>]...
```

**Comment by MorrisJobke** [comment]
@benedigtk Do you maybe want to check this out?

**Comment by benediktg** [comment]
@MorrisJobke Even when I run `occtl music:scan -vvv benedikt` (`occtl` is my alias for `sudo -u www-data php /var/www/owncloud/occ`) the response is just 
```
Start scan for benedikt
```

**Comment by JetUni** [comment]
If there's anything I can do, let me know what and I'll do my best to help.

**Comment by MorrisJobke** [comment]
@JetUni How many music files do you have?

**Comment by JetUni** [comment]
Around 90GB or so, but it hasn't gone through many of them before getting that error.

**Comment by mossholderm** [comment]
I'm seeing the exact same issue.  I tried, on a lark, to remove all music files from my account, and still got the exact same result.  After truncating all of the oc_music_* tables in the database, and re-scanning, it all worked as expected.

**Comment by paulijar** [comment]
This happens when the database contains two or more album entries with the same name, artist, and disc number. The database is not supposed to ever end up into this state, but my best guess is that it might occur if more than one thread executes Scanner.update() method simultaneously. There should probably be some kind of locking mechanism making this method a critical section.

I ran into this problem when I placed ~200 music tracks to the ownCloud sync folder on PC, and then modified the ID3 tags of all those tracks with mass tagger software while the uploading to ownCloud was still ongoing. There are probably also other means to make this happen, e.g. #322.
