### ISSUE TITLE
Most Albums Suddenly Showing Up As "Unknown Artist"

### ISSUE THREAD

**Issue by zerojay** [owncloud/music#561]
Since upgrading to 0.3.12 and 0.3.13, I'm finding that suddenly a lot of tracks that had previously scanned properly are now showing up as Unknown Artist. When looking at the actual tracks for one of these albums though, I can see that it is showing the proper artist name next to the song name in parentheses, so the scanner appears to be reading the artist tags properly, but it's just not grouping them properly.

I would say that of my few hundred albums, only about 30-40 are under the proper artist name, all the rest are listed under Unknown Artist right now.

This apparently has been happening for a while with others as well and was reported on the Owncloud Apps page for Music, as seen in a thread titled "3.12 - a lot of unknown artists": https://apps.owncloud.com/content/show.php?content=164319&forumpage=10

Ampache players such as Just Player and Power Ampache show the songs under the proper artist names - likely because they are handling arranging albums on their own.

**Comment by paulijar** [comment]
The release 0.3.12 brought the support for the "Album artist" tag but it came with a problem: if your track does not specify this tag, the track will be listed under "Unknown Artist", even if the track would have the "Track artist" tag set.

The above mentioned issue was fixed by #524 which is included in 0.3.13. However, the fix is applied only at the time of database creation, and the 0.3.13 release does not trigger automatic recreation (it really should but this was forgotten).

You should be able to fix your problem by resetting the database. This can be made for all users with the occ command line utility or per-user by changing the "music path" setting of the Music app to something else, and then back to original. Do not use the occ tool to erase the database of a single user because there is another bug... Step-by-step instructions:
1. Click the user name on top-right corner and select 'Personal'
2. Scroll down to 'Music'
3. Click 'Path to your music collection' and select any folder
4. Click again 'Path to your music collection' and select your original path (user root folder by default)
=> The database is recreated the next time you navigate to the Music app.

**Comment by zerojay** [comment]
That worked for me, thank you.
Perhaps it would be good to call this out in release notes or something on the next release.
