### ISSUE TITLE
Album covers load very slow

### ISSUE THREAD

**Issue by artemanufrij** [owncloud/music#570]
I use `music` on nextcloud 12. Every time when I open music-app album covers load very slow.

**Comment by paulijar** [comment]
@artemanufrij Thanks for your report. How slow exactly is "very slow"? Are your cover images embedded in the audio files, or do you have separate image files in your audio folders? Which browser?

I was testing a bit with collection of ~200 albums, each having embedded cover art. I noticed that there is a big difference between Firefox and Chrome: For Chrome, it takes some 40-50 seconds before all the covers get loaded every time I open the Music app. On Firefox, it takes about the same on first load of Music app, but on consecutive loads the covers appear instantly. So it seems to me that Firefox is able to cache the images but Chrome is not.

**Comment by artemanufrij** [comment]
hey @paulijar see my screencast:
[cloud music.webm.zip](https://github.com/owncloud/music/files/1184968/cloud.music.webm.zip)

tested on chromium and epiphany

**Comment by paulijar** [comment]
@artemanufrij Thanks. Your screencast seems pretty similar as what I saw on Chrome.

**Comment by paulijar** [comment]
I changed the way the cover images are loaded for the brand new release 0.4.2 (https://github.com/owncloud/music/releases/tag/v0.4.2): all previously cached cover images are now embedded directly to the collection.json describing the tree structure and contents of the music collection. This makes them appear instantly when the page is loaded. If the images are not already cached, the behavior is the same as before.

The downside of this is that more data has to be downloaded before anything can be shown. This may be significant on very slow connections but should be a non-issue with decent bandwidth.

**Comment by artemanufrij** [comment]
@paulijar thank you for very fast implementation:
but after update I see only a spinner on all my devices. Tested on IE11, Chrome, UbuntuPhone:

![spinner](https://user-images.githubusercontent.com/16517095/28813136-420cfcd0-7698-11e7-948f-ddde80dd32e0.png)

**Comment by paulijar** [comment]
@artemanufrij Okay, sorry to hear that :(. Is there any errors on the web browser console (F12) or in nextcloud.log? Which DB backend are you using?

Does it help if you erase the music database and let it be regenerated? You can do this either from command line with
``` occ music:reset-database <username>``` 
or from web interface by browsing to "cogwheel" > Personal > Music and changing the "Path to your music collection" to something else and then back to original.

Also, if you cover images are very large compared to your network connection speed, then the loading time could be quite long before all the data is transferred. On the Network tab of the browser develop tools, can you locate row "collection"? Did it load and what is its size?

**Comment by artemanufrij** [comment]
@paulijar I will check it when I'm back home

**Comment by paulijar** [comment]
I managed to reproduce the "loading indefinitely" issue by placing a 7 MB image file into my audio folder so that it was used as cover for 4 albums. It seems to me that the web server's connection to MySQL server times out when the size of the collection.json is large enough. I hadn't taken into account that people could actually have very large cover images, either on purpose or by accident.

Obviously, such large images should not be embedded into collection.json; it only makes sense for smallish images. Also, it would make sense to create shrunk down versions of the overly large images, but I need study how to do such thing and what would be the cost.

**Comment by artemanufrij** [comment]
here is an error (Chromium)

![bildschirmfoto von 2017-08-01 19 21 26](https://user-images.githubusercontent.com/16517095/28837904-c4e3d57e-76ee-11e7-961b-2f8706d9e82d.png)

**Comment by artemanufrij** [comment]
I've tested last release... It works now! thanks!

**Comment by paulijar** [comment]
@artemanufrij Great! I was just in the middle of writing here that I made the quick fix release 0.4.3 when your reply arrived :).

In this release, I tweaked the cover image embedding logic so that
1. Pictures larger than 100 KB are never embedded
2. At maximum 3 MB worth of pictures may be embedded; any remaining pictures after hitting the limit are loaded separately.

So if the user has only large cover images, then the loading will be as slow as in 0.4.1. But if even some of the images are smaller than 100 KB, then those should become visible quicker than in 0.4.1 and hence also the overall time to load all the images is reduced.

I'm closing this issue now as the situation has certainly improved from 0.4.1. I still may implement more related improvements at some later time.
