### ISSUE TITLE
Can't Enable Music

### ISSUE THREAD

**Issue by jimmy5670** [owncloud/music#573]
### I'm using Nextcloud and want use Music APP, after install app, It shows error message below:

> An exception occurred while executing 'CREATE UNIQUE INDEX user_id_hash_idx ON oc_music_artists (`user_id`, `hash`)': SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'guest-' for key 'user_id_hash_idx'

### 
I'm trying use SSH console interface and enable Music APP by occ command,
reply more error message with red background below:

>  [Doctrine\DBAL\Exception\UniqueConstraintViolationException]
>   An exception occurred while executing 'CREATE UNIQUE INDEX user_id_hash_idx ON oc_music_artists (`user_id`
>   , `hash`)':
>   SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'guest-' for key 'user_id_hash_idx'

>   [Doctrine\DBAL\Driver\PDOException]
>   SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'guest-' for key 'user_id_hash_idx'

>   [PDOException]
>   SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'guest-' for key 'user_id_hash_idx'

### 
I guess there is some SQL command error, but I'm not sure how to fix.

Thanks

**Comment by paulijar** [comment]
@jimmy5670 You have probably had an older version of Music app installed previously and have now updated to 0.4.x? Which Nextcloud version are you using?

The problem is that the database contents created by the older version do not fulfill the constraints set in the new version. The update process is supposed to erase the old data from the database, but this does not work on older cloud versions. For ownCloud, the version has to be at least 9.1.0 for the update to work correctly but I don't know what is the required version for Nextcloud. It works at least on NC 12.

In case you are running an older cloud, you need to erase the database manually. One way to do this is with occ:
```sudo -u ww-data ./occ music:reset-database --all```
I think you need to have a working installation of Music app for this to work. If you are already in the middle of the update problem, this might not be available. If you have a command line interface to you SQL server, you can also erase the data by hand:
```
delete from oc_music_albums;
delete from oc_music_ampache_sessions;
delete from oc_music_ampache_users;
delete from oc_music_artists;
delete from oc_music_cache;
delete from oc_music_playlists;
delete from oc_music_tracks;
```
The prefix of the table name may also be something else than 'oc_' if configured so on your installation. If the table oc_music_cache does not exist yet, just skip it.

**Comment by jimmy5670** [comment]
@paulijar 
I am using Nextcloud version 12, and I was use Owncloud long time ago and had install older version of Music APP, then I switched to nextcloud, I think that's why the errors show up,
thanks a lot your clear hints, after I erase SQL server the Music APP can be enable correctly.

**Comment by paulijar** [comment]
@jimmy5670 Okay, I'm glad it helped.

I suspect that in you case it's possible that Nextcloud did not realize that there were left-overs from the old Music app installation in the DB. In this case, the version migration logic would not run and the automatic erasing of incompatible data would not happen.

**Comment by JLagrue** [comment]
Please forgive the simplistic question:

How do I get into the command line interface to the Nextcloud database so that I can remove the tables, as detailed above?

**Comment by paulijar** [comment]
@JLagrue That depends on you installation. I'm using mysql database and I can access the interface from Linux command line by running  `mysql -u <db_username> -p<db_password> <db_name>`, for example `mysql -u owncloud_user -pSeCrEtPaSs123 owncloud_db`.

**Comment by dgriswo** [comment]
Sorry for the necro post, found this with a google search.

@paulijar answer fixed my issue. Slight tweak to the reset command if people are copy/pasting.
`sudo -u www-data ./occ music:reset-database --all`
