### ISSUE TITLE
Scanning Music files is very slow

### ISSUE THREAD

**Issue by mmattel** [owncloud/music#579]
Mount already scanned 
Music scanning needs about 1-5s per file, sometimes much longer.
Files reside on a SMB share, access is very fast

![image](https://user-images.githubusercontent.com/3321281/30588968-1201744a-9d39-11e7-8ffc-776f69b1200d.png)

**Comment by paulijar** [comment]
It shouldn't take that long. I'm running cloud instance on a low-end server (RaspberryPi 3) and scanning takes about 2-3 seconds per 10 files. Which database management system are you using?

**Comment by mmattel** [comment]
My system is a 2GHz 4 core XEON 1.4 GB Ram
Ubuntu 16.04, PHP 7, Mysql, nginx
Redis Stat shows 200-300 commands per second but peaks to many hundreds
Not much memory needed
But I see a lot of CPU on php-fpm during the run
No difference when run via browser or ./occ

**Comment by paulijar** [comment]
I'm using combination of MySQL + ngingx as well, so that shouldn't be the issue. I'm using PHP 5.x but I can't see how that could make any major difference. High CPU load during scanning is normal, I see php5-fpm taking ~50% of CPU. 

I assume you are using a recent version of the Music app. Have you previously tested any earlier versions, and is this problem present only on the recent version(s) or has been there always? 

Using SMB share for files is something which I haven't tested, so that could be potentially significant. Are you using the "External storage" feature of ownCloud/Nextcloud to mount the storage to your cloud? Or have you mounted the SMB share to your file system and placed the whole OC data folder there?

Have you checked if there's anything interesting in the owncloud.log?

**Comment by mmattel** [comment]
Nothing in the log
Load is about the same
It is the latest available via the market app, not tested earlier versions...

**Comment by martinsah** [comment]
Scanning is very slow for me too - I'm running on AWS with S3 backend. It takes about 2-3 seconds per file.
I already scanned once a few weeks ago and the music app is asking me to scan again. Is it actually copying every file in entirety from the backend each time it does a scan?

**Comment by paulijar** [comment]
@martinsah No files are being copied during the scanning but each file needs to be opened and at least the first 8 kB of the file contents are read. Maybe your setup has significant overhead opening a file, like a need to decrypt the file or something like that? Another possibility is that the slowness comes from the database management system when the app stores the metadata extracted from the files. Which database are you using?

If you have already scanned the library successfully but the app notifies you again about unscanned files, the chances are that the app has detected new music files in your file system. In most cases those get scanned automatically on the background, but that doesn't happen for example in case you restore an audio file from the deleted files. If that is the case, then the new scan should be fast as it only scans the new file(s). Another possibility is that you have changed the music collection path from the Personal settings; in that case the whole library needs to be rescanned from scratch.

**Comment by martinsah** [comment]
@paulijar I'm using MySQL. The resource utilization is relatively low on my server. (Linux) CPU load is ~0.08 during scan.

I did fill in the "Music" folder field so I understand why it's rescanning. My fault. The path didn't change, I just filled in the field. Maybe it should only scan if the path actually changed.

I can verify that it is indeed re-reading entire files based on AWS metrics. I think this is an issue with the backend not allowing partial reads but I can't verify this at the moment. I will try to find out if this is the case. You may not be interested if this is a backend issue and not a Music specific issue?

**Comment by kc0bfv** [comment]
Hey guys, I have this issue too - but also with s3 as external storage instead of smb.  I'm wondering if this is related to an error I see in my log files when scanning (and taking other actions) - fseek(): stream does not support seeking...  That's already issue 8275 on nextcloud.  https://github.com/nextcloud/server/issues/8275

@martinsah - if that's your issue too it looks like help is coming: https://github.com/nextcloud/server/pull/20033/commits/14401efb0f6792415f15c92c1db07fe9e25ea466

When trying to fix/diagnose my s3 issue, I ran into this SMB problem on another audio player: https://github.com/Rello/audioplayer/wiki/External-Storage

Different app - but similar issues...  @mmattel I wonder if the recommendation there helps with your problem.

**Comment by martinsah** [comment]
@kc0bfv  thanks for the notice! I will try it out. Are you using AWS S3? It should be trivial to create a bucket and monitor usage stats if you have access and proper rights.

**Comment by kc0bfv** [comment]
I'm not, I'm using another Ceph-based service that's really intended for
shared hosting service users...  I have some usage stats available, but
very course, not like AWS's setup.  I can tell that I don't seem to be
downloading huge chunks of MP3s like I used to be, and little more.

**Comment by paulijar** [comment]
I think it's time to close this old issue. The recent versions of Nextcloud support `fseek` also on AWS S3 storage which should make scanning fast on such setups. On the other hand, `fseek` may or may not work on SMB storages, depending on the cloud version and smbclient setup installed; I don't know which are working combinations today but that's out-of-scope of the Music app.

Finally, if the metadata scanning cannot be made to work with satisfactory performance on some system, the Music v1.5.0 offers the possibility to disable the metadata extraction altogether. In that case, the artist/album/song names are taken from the file and folder names alone. Not having the metadata at hand prevents using some of the features of the Music app (like browsing by genres, showing release years) but this may be less of a problem than scanning taking forever.
