### ISSUE TITLE
No browser playback in Chromium

### ISSUE THREAD

**Issue by Biont** [owncloud/music#595]
Playback is working fine in Firefox, whereas in Chrome, I get this error whenever I try to start playback:

```
Refused to load media from 'data:audio/wave;base64,/UklGRiYAAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YQIAAAD//w==' because it violates the following Content Security Policy directive: "media-src 'self'".
```

Please let me know if I and how can provide more information.

My setup:

* Music 0.5.4
* Nextcloud 12.0.3
* PHP 7.1.11

* Firefox 57
* Chromium 62.0.3202.94

**Comment by paulijar** [comment]
The Content Security Policy issue should have got fixed with the commit 5c310e14ef which is not yet included in v0.5.4. I'm not certain, though, if it actually fixes the playback because in my environment I saw the CSP error on Chrome but the music was still playing back fine.

I suggest you test this with the next release. Or if you like, you may of course pull the development version from git and test it right away. Or even apply the changes from the mentioned commit manually, as it's a simple 3-line addition.

**Comment by Biont** [comment]
I added those 3 lines to the correct spot in appinfo.php and yup, the warning is now gone. Still no playback though, and nothing relevant in the logs.

This is weird. Can you reproduce this?

**Comment by paulijar** [comment]
Have you tested Chrome browser or only Chromium? The significant difference is that Chrome has many built-in audio decoders but Chromium is distributed without them. Hence, we need to rely on the javascript library aurora.js when playing music on Chromium, and only mp3 and flac file formats are supported there. The aurora.js library also has a known bug that some mp3 files fail to play (although most should play fine).

**Comment by Biont** [comment]
I only have Chromium on my laptops, but Chrome on Android is playing my sond just fine. So it could be that it's just broken on Chromium. I only have mp3 and flac, though. Shouldn't those work?

If it's at all helpful, this is the JS log I see when I try to play a song via the file browser:

```
Using sm2 for type audio/mpeg URL /remote.php/webdav/Musik/C%C5%93ur%20de%20Pirate/Child%20of%20Light/06%20The%20Horn%20and%20the%20Spear%20for%20Cho.mp3?requesttoken=qsoB4A6ZBOC4jYD%2Fho8svA2IFHzEMlBtrWhoU30eENs%3D%3AwvpoqXegUa7S%2FqvLyeRD2lveejfrR2EimzldH05mabU%3D
soundmanager2-jsmin.js?v=170100a3be8e1fb137e5f5ed621311fe-7:34 soundManager.createSound(): ownCloudSound (/remote.php/webdav/Musik/C%C5%93ur%20de%20Pirate/Child%20of%20Light/06%20The%20Horn%20and%20the%20Spear%20for%20Cho.mp3?requesttoken=qsoB4A6ZBOC4jYD%2Fho8svA2IFHzEMlBtrWhoU30eENs%3D%3AwvpoqXegUa7S%2FqvLyeRD2lveejfrR2EimzldH05mabU%3D)
soundmanager2-jsmin.js?v=170100a3be8e1fb137e5f5ed621311fe-7:34 ownCloudSound: Merged options: Object
soundmanager2-jsmin.js?v=170100a3be8e1fb137e5f5ed621311fe-7:34 ownCloudSound: togglePause()
soundmanager2-jsmin.js?v=170100a3be8e1fb137e5f5ed621311fe-7:34 ownCloudSound: play(): Attempting to load
soundmanager2-jsmin.js?v=170100a3be8e1fb137e5f5ed621311fe-7:34 ownCloudSound: load (/remote.php/webdav/Musik/C%C5%93ur%20de%20Pirate/Child%20of%20Light/06%20The%20Horn%20and%20the%20Spear%20for%20Cho.mp3?requesttoken=qsoB4A6ZBOC4jYD%2Fho8svA2IFHzEMlBtrWhoU30eENs%3D%3AwvpoqXegUa7S%2FqvLyeRD2lveejfrR2EimzldH05mabU%3D)
soundmanager2-jsmin.js?v=170100a3be8e1fb137e5f5ed621311fe-7:34 ownCloudSound: loadstart
soundmanager2-jsmin.js?v=170100a3be8e1fb137e5f5ed621311fe-7:34 ownCloudSound: durationchange (244056)
soundmanager2-jsmin.js?v=170100a3be8e1fb137e5f5ed621311fe-7:34 ownCloudSound: loadedmetadata
soundmanager2-jsmin.js?v=170100a3be8e1fb137e5f5ed621311fe-7:34 ownCloudSound: loadeddata
soundmanager2-jsmin.js?v=170100a3be8e1fb137e5f5ed621311fe-7:34 ownCloudSound: canplay
soundmanager2-jsmin.js?v=170100a3be8e1fb137e5f5ed621311fe-7:34 ownCloudSound: onload()
soundmanager2-jsmin.js?v=170100a3be8e1fb137e5f5ed621311fe-7:34 ownCloudSound: progress, 33% loaded
soundmanager2-jsmin.js?v=170100a3be8e1fb137e5f5ed621311fe-7:34 ownCloudSound: progress, 43% loaded
soundmanager2-jsmin.js?v=170100a3be8e1fb137e5f5ed621311fe-7:34 ownCloudSound: progress, 52% loaded
soundmanager2-jsmin.js?v=170100a3be8e1fb137e5f5ed621311fe-7:34 ownCloudSound: progress, 61% loaded
soundmanager2-jsmin.js?v=170100a3be8e1fb137e5f5ed621311fe-7:34 ownCloudSound: progress, 66% loaded
soundmanager2-jsmin.js?v=170100a3be8e1fb137e5f5ed621311fe-7:34 ownCloudSound: suspend
soundmanager2-jsmin.js?v=170100a3be8e1fb137e5f5ed621311fe-7:34 ownCloudSound: Playback suspended
```

I loaded some more albums to check if it's just those few song I had on my server, but none will play on Chromium

**Comment by paulijar** [comment]
Actually, I need to correct my statement about Chromium a bit. Some versions (or installations?) of Chromium seem to have the audio codecs. I have Chromium 60.x on one Windows PC and it has the codecs. On another Windows PC, I have Chromium 55.x with no codecs. From your browser log, we can see that soundmanager2 is being used instead of aurora.js, so apparently your browser has the codecs. You can also check from https://html5test.com, which audio formats are natively supported by your browser.

The bad news is that I have no idea what is wrong in your system. I get the same browser log output when using a browser which includes the codecs, but the audio plays back fine. I get even the last log line "Playback suspended" which doesn't really make sense because the playback is not suspended. Looking at the codes of the soundmanager2 library, I believe that printing this line is a bug in the library but it shouldn't cause any other problems except the misleading log line.

**Comment by Biont** [comment]
I am sorry. I am using an extension called "Disable HTML5 Autoplay" to prevent sites from shoving loud music and ads in my face when I load a page. For some reason, this extension also blocked playback when I tried to play songs in NC.

http://www.schillmania.com/projects/soundmanager2/ shows the same behaviour, so maybe this isn't even something you can control with that library. Ideally, this would not happen as it's absolutely intended behaviour. Maybe there's something you can do about it, but as far as this issue is concerned, it was an error on my end. Sorry for bothering you with it.

**Comment by paulijar** [comment]
Okay, no problem. I'm glad we got this figured out.

I can't see, how an extension could reliably distinguish the starting of audio playback from javascript automatically or based on user-action. Hence, I'm not surprised that the extension may make mistakes. Ideally, that kind of blocker extensions should have a white-list feature where you could disable the extension on desired sites.
