### ISSUE TITLE
occ music:scan issue

### ISSUE THREAD

**Issue by mmattel** [owncloud/music#602]
When you run ``./occ music:scan user_1,user_2`` following issue takes place:

``user_1,user_2`` is mistyped from the command line.
It should be ``user_1`` ``user_2``, no comma but a blank in between or only one user.
It treats the statement ``user_1,user_2`` as a user !
Looking into the folder data, you then see now a new user named ``user_1,user_2`` but this user is not recognized by owncloud core. You just can delete him manually.

Please improve user handing from the command line

**Comment by paulijar** [comment]
Thanks for the report. It seems to happen so that if you give any non-existing user as argument to `music:scan`, a directory with that name and a subdirectory `files` gets created. I assume that happens when the Music app calls `\OC_Util::setupFS($user);` to access the file system of that particular user. Obviously, we should check the existence of the user prior to calling this, and print an error message if there is no such user. Should be rather easy to fix.
