### ISSUE TITLE
translation template folder not inline with perl script

### ISSUE THREAD

**Issue by greku** [owncloud/music#623]
The l10n.pl script (and therefore make) generates the translation template in "templates" folder. However it is currently committed in "Templates" folder. Can we move the music.pot file to "templates" folder ?

**Comment by paulijar** [comment]
Yes, probably it should be "templates" instead of "Templates".  The lower-case name is referenced here: https://github.com/owncloud/music/blob/master/l10n/.tx/config#L7. I wonder, if this is the reason why the changes in the template at not currently being synced to the Transifex service for translation.
