### ISSUE TITLE
Mobile View of shared links dont work -> blank folder structure

### ISSUE THREAD

**Issue by xXSTrikeXx** [owncloud/music#629]
Regarding the app is responsible for my error on nextcloud, I opening here now a new issue, so I can close it in the core.
Reference: #8530
https://github.com/nextcloud/server/issues/8530

**Comment by paulijar** [comment]
I couldn't reproduce the issue with Chrome on Android 7.1.1. I tested with Nextcloud 12 and 14.0.0-alpha.

What makes you believe that this is caused by the Music app? Was the issue solved for you by disabling Music?

Do you see the problem only on Android or also on desktop browser if you shrink the window to be as narrow as on mobile?

**Comment by xXSTrikeXx** [comment]
What makes you believe that this is caused by the Music app? Was the issue solved for you by disabling Music?

Yep after I disable music app it is working. Only on Android and IOS.

**Comment by paulijar** [comment]
I now tested this with NC13. On first try, the shared folder view did not show at all but there was a blank page with error message 
```
Internal Server Error

The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log.
```

After a couple of reloads, the view showed up fine. Afterwards, I found error like this in the nextcloud.log:
```
{"reqId":"Niz2Yrn7zKClqYen9WG3","level":3,"time":"2018-02-28T21:35:57+02:00","remoteAddr":"91.158.223.156","user":"--","app":"core","method":"GET","url":"\/nextcloud\/index.php\/s\/cQ14xDelbssNe0l","message":"Exception: {"Exception":"OCP\Lock\LockedException","Message":""/files" is locked","Code":0,"Trace":"#0 /var/www/html/nextcloud/lib/private/Files/View.php(1142): OC\Files\View->changeLock('/files', 2)
#1 /var/www/html/nextcloud/lib/private/Files/View.php(267): OC\Files\View->basicOperation('mkdir', '/files', Array)
#2 /var/www/html/nextcloud/lib/private/Files/Node/Folder.php(160): OC\Files\View->mkdir('//files')
#3 /var/www/html/nextcloud/apps/music/utility/scanner.php(569): OC\Files\Node\Folder->newFolder('/files')
#4 /var/www/html/nextcloud/apps/music/hooks/filehooks.php(62): OCA\Music\Utility\Scanner->resolveUserFolder(false)
#5 [internal function]: OCA\Music\Hooks\FileHooks::updated(Object(OC\Files\Node\File))
#6 /var/www/html/nextcloud/lib/private/Hooks/EmitterTrait.php(99): call_user_func_array(Array, Array)
#7 /var/www/html/nextcloud/lib/private/Hooks/PublicEmitter.php(36): OC\Hooks\BasicEmitter->emit('\OC\Files', 'postWrite', Array)
#8 /var/www/html/nextcloud/lib/private/Files/Node/Root.php(136): OC\Hooks\PublicEmitter->emit('\OC\Files', 'postWrite', Array)
#9 /var/www/html/nextcloud/lib/private/Files/Node/Folder.php(183): OC\Files\Node\Root->emit('\OC\Files', 'postWrite', Array)
#10 /var/www/html/nextcloud/lib/private/Files/SimpleFS/SimpleFolder.php(83): OC\Files\Node\Folder->newFile('77985e06-jquery...')
#11 /var/www/html/nextcloud/lib/private/Template/SCSSCacher.php(206): OC\Files\SimpleFS\SimpleFolder->newFile('77985e06-jquery...')
#12 /var/www/html/nextcloud/lib/private/Template/SCSSCacher.php(118): OC\Template\SCSSCacher->cache('/var/www/html/n...', '77985e06-jquery...', 'jquery.ocdialog...', Object(OC\Files\SimpleFS\SimpleFolder), '/nextcloud/core...')
#13 /var/www/html/nextcloud/lib/private/Template/CSSResourceLocator.php(109): OC\Template\SCSSCacher->process('/var/www/html/n...', 'core/css/jquery...', 'core')
#14 /var/www/html/nextcloud/lib/private/Template/CSSResourceLocator.php(61): OC\Template\CSSResourceLocator->cacheAndAppendScssIfExist('/var/www/html/n...', 'core/css/jquery...')
#15 /var/www/html/nextcloud/lib/private/Template/ResourceLocator.php(78): OC\Template\CSSResourceLocator->doFind('css/jquery.ocdi...')
#16 /var/www/html/nextcloud/lib/private/TemplateLayout.php(266): OC\Template\ResourceLocator->find(Array)
#17 /var/www/html/nextcloud/lib/private/TemplateLayout.php(182): OC\TemplateLayout::findStylesheetFiles(Array)
#18 /var/www/html/nextcloud/lib/private/legacy/template.php(207): OC\TemplateLayout->__construct('error', '')
#19 /var/www/html/nextcloud/lib/private/Template/Base.php(132): OC_Template->fetchPage()
#20 /var/www/html/nextcloud/lib/private/legacy/template.php(351): OC\Template\Base->printPage()
#21 /var/www/html/nextcloud/index.php(65): OC_Template::printExceptionErrorPage(Object(OCP\Lock\LockedException))
#22 {main}","File":"/var/www/html/nextcloud/lib/private/Files/View.php","Line":1978}","userAgent":"Mozilla\/5.0 (Linux; Android 7.1.1; E5823 Build\/32.4.A.1.54) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.137 Mobile Safari\/537.36","version":"13.0.0.14"}
```

NC13 seems to be notifying the Music app about file change in its internal generated css files. The exception probably happens because those files have no owner and the Music app is prepared to handle only notifications about user files.  I'm not certain if this is intentional or a bug on the core to send these notifications but obviously we need to add some sanity checking to the file modified hook in the Music app. 

Then I enabled also the Audio player app and now I could see an empty view like in the screenshot of nextcloud/server#8530. But only if I had both Audio player and Music apps enabled. If I disabled either, the view showed up fine also on Chrome for Android. I find it likely that this is just another symptom of the same underlying issue as described above. I just don't quite understand, what is the connection to Audio player. Anyway, as we now have a way to reproduce the issue, I'm sure it can be fixed too.

**Comment by xXSTrikeXx** [comment]
I just want to add that the music is locally added on an external HDD formated in NTFS.

**Comment by paulijar** [comment]
After further study, it seems that the reported bug is unrelated to the problem with FileHooks which I described above. I made a fix for the FileHooks but can still see the "files not shown on shared view" problem. I noticed that the bug can be reproduced also on the desktop Chrome when you activate the responsive design mode from the develop tools. This makes it a lot easier to debug and I could now see an error message in the console:
```
soundmanager2-nodebug-jsmin.js:61 Uncaught TypeError: c.html5.canPlayType is not a function
    at Y (soundmanager2-nodebug-jsmin.js:61)
    at w.canPlayMIME (soundmanager2-nodebug-jsmin.js:28)
    at PlayerWrapper.canPlayMIME (playerwrapper.js:97)
    at underscore.js:73
    at underscore.js:227
    at Function._.each._.forEach (underscore.js:153)
    at Function._.filter._.select (underscore.js:226)
    at registerFileActions (files-music-player.js:332)
    at HTMLDocument.<anonymous> (files-music-player.js:402)
    at j (jquery.js:3099)
```
The root cause might now be that both Audio player and Music app use the same 3rd party library soundmanager2 to play music and somehow they now interfere each other. I still don't understand, why this happens only in the mobile view on Chrome. Maybe it's some timing issue.

**Comment by paulijar** [comment]
Should be fixed now. The fix will be included in the next release.

**Comment by michaelof** [comment]
One short question:

"The fix will be included in the next release.": Of Music App, or of (whole) nextapp?

Not sure if it's irrelevant for this issue or maybe already known, but this issue only happens on Mobile (Android) with Chrome. Firefox Mobile on same smartphone (Android 6.0) dies NOT show this issue

**Comment by michaelof** [comment]
s/nextapp/nextcloud, sorry for the typo

**Comment by paulijar** [comment]
@michaelof In the next release of the Music app. The release does not yet have a planned date but if it doesn't happen during March then probably during April.

**Comment by paulijar** [comment]
I didn't have time during March or April but now the new Music app release v0.6.0 is finally out, including the fix for this issue.
