### ISSUE TITLE
Navigating away from large playlist is gradually becoming slower

### ISSUE THREAD

**Issue by paulijar** [owncloud/music#635]
_**Edit:** This issue was originally reported for the "All tracks" view which is reflected below. After #647, the issue is no longer present in "All tracks" but can still be reproduced on custom playlists if they have thousands of tracks. The title was updated to reflect this._

This bug was discovered when testing #625 and has been already discussed there. It, however, doesn't seem to be caused by the changes of that PR but is reproducible also on e.g. release v0.5.6.

When navigating several times back and forth between the *Albums* and *All tracks* views, the *All tracks* view takes more and more time to deactivate. To see this, there has to be more than a handful of tracks in the library and the effect is much more visible on Firefox than on Chrome. The time taken to navigate to the opposite direction does not change.

Here's some numbers of the time it takes to navigate from *All tracks* to *Albums* on Firefox. The time has been measured (by hand) from the click of the navigation pane to the moment when the first albums become visible. The collection contained 1954 tracks.
```
#  Time
1  1.4 s
2  1.3 s
3  1.6 s
4  1.6 s
5  1.5 s
6  2.7 s
7  3.1 s
8  3.2 s
9  3.7 s
10 3.8 s
11 4.1 s
12 4.2 s
13 4.7 s
14 4.9 s
15 5.1 s
16 5.4 s
17 5.7 s
18 5.9 s
19 6.2 s
20 6.4 s
```

Edit 2021-12-06: This issue is still reproducible using a 2000-track playlist on Music v1.5.0.

**Comment by Biont** [comment]
I mentioned in the other issue:

>I added some (jqLite) event listeners in #614 that I do not properly cleanup in '$destroy',

However, this is untrue as I `element.off()` is called in the callback. I will still investigate since there's a good chance the problem is caused by the new track list directive

**Comment by Biont** [comment]
After some investigation, I have arrived at similar conclusions as @greku in https://github.com/owncloud/music/pull/625#issuecomment-372460552 .

It is not the loading of the album list that gets slower, it is the **un**loading of the track list. At least that's what profiling in the DevTools seems to suggest (although I'm not yet convinced).

Could anyone tell me what [this piece of code](https://github.com/owncloud/music/blob/e1925511e5d5077d602c7e4be37e3b6a934cab39/js/app/controllers/playlistviewcontroller.js#L194-L202) is even doing?
```js
function showLess() {
	$scope.incrementalLoadLimit -= INCREMENTAL_LOAD_STEP;
	if ($scope.incrementalLoadLimit > 0) {
		$timeout(showLess);
	} else {
		$scope.incrementalLoadLimit = 0;
		$rootScope.$emit('viewDeactivated');
	}
}
```


I believe it is the `$timeout` used here that makes unloading tracks appear to be the culprit while it probably just hides that the _real issue_ is in rendering the UI.
The way `$timeout` is used results in [setTimeout being called without a delay](https://github.com/angular/angular.js/blob/7df29521d8c1c494f615c49d6c2e1e267e3a6be5/src/ng/browser.js#L321-L330) which is a way of [deferring an action until the UI thread is ready again](https://stackoverflow.com/a/9084320)

I might be wrong, but it looks to me as if the unloading of tracks really only shows up on the profiler because it's busy waiting for the UI thread for so long. And since the code above does not make much sense to me, I replaced it with

```js
function showLess() {
	$scope.incrementalLoadLimit = 0;
	$rootScope.$emit('viewDeactivated');
}
```

to get rid of the recursive calls to `$timeout`. As expected, the slowdowns still appear. I will continue to investigate.

**Comment by paulijar** [comment]
The point of the whole "incremental load" construct is to divide the adding and removing of the tracks to/from the UI to multiple digest cycles. In case there are thousands or tens of thousands of tracks, removing those from the DOM takes a significant amount of time. If that would happen in one step, the whole web browser would be unresponsive for the duration of that operation. If that unresponsiveness lasts long enough, the browser will ask the user if the script should be terminated.

With the "incremental load", both adding and removing of the tracks happens in batches of 1000 tracks. The UI stays responsive and the user can, for example, start navigating from *Albums* to *All tracks*, change his mind before *All tracks* is fully loaded and choose to navigate back to *Albums* or to some other view.

Different browsers execute javascript with varying speed. Chrome seems to be here faster than Firefox which is faster than Edge which is faster than IE. This means that on IE the same responsiveness problems become visible with much smaller set of tracks but even on Chrome those do exists, provided that the collection is large enough.

**Comment by paulijar** [comment]
After #647, this is no longer an issue in the "All tracks" view. It's still possible to reproduce the same symptoms with the user-created playlists if the playlist contains thousands of tracks.

**Comment by paulijar** [comment]
I could no longer reproduce this problem using Nextcloud 27, Music v2.0.1, and Firefox 130.0. However, keeping everything else the same but using Chrome 128.0, the problem can still be seen on the 2000 track playlist when navigating dozens of times back and forth. This makes me think that this is mainly a browser-side issue, where the large number of HTML elements and/or ng bindings causes a performance problem for the garbage collection.

Anyway, getting into this problem nowadays requires such extreme torture testing that it's unlikely that many real-life users will ever notice this. Hence, I see no longer reason to keep this old issue open.
