### ISSUE TITLE
Reading through the app doesn't work

### ISSUE THREAD

**Issue by Telkas** [owncloud/music#650]
I can play music with files explorer.
Firefox console 

> SoundManager 2: No Flash detected. Trying HTML5-only mode.  soundmanager2-jsmin.js:34
> SoundManager V2.97a.20170601 (HTML5-only mode) + html5PollingInterval (200ms)  soundmanager2-jsmin.js:34
> SoundManager 2 HTML5 support: mp3 = true, mp4 = true, ogg = true, opus = true, wav = true, flac = true  soundmanager2-jsmin.js:34
> SoundManager 2: Ready. ✓  soundmanager2-jsmin.js:34

But through the app

"Using sm2 for type audio/mpeg URL http://xxxxxxxx.xxx/remote.php/webdav/....  app.js:1571
SM2: sound load error  app.js:1609

Thanks

**Comment by paulijar** [comment]
Thanks for the report.

This sounds quite weird. Does this happen with all of your files? Does this happen on browsers other than Firefox?

When you open the browser developer tools and the "Network" tab, can you see the music file being downloaded? If yes, then does the file seem to download successfully or is there an error?

If you compare the music file download on the "Network" tab when playing from the Music app and when playing from the Files app, can you see any differences. E.g. is one downloading the file using different URL than the other?

(Sorry for the high number of questions, you don't need to answer all of them at once if you are busy :) )

**Comment by Telkas** [comment]
Thanks for your reply,
I've this issue with all browsers on all platforms (only tested on debian and android to be exact... ).
I can see the download when I play with Files app, but not when I try to play with Music app....
I've the same issue with the update of Music app 0.7.0 .
I use Nextcloud 13.0.4 .
I can't test with all my files... , but with a lot of them I've this issue (I've never been able to read with Music app).
It works perfectly with ampache player also, it is currently my alternative.
Can I read the number of tracks/albums/artists with occ command ? I don't know how many tracks I've but around 90Gb.

Thanks for your help and your work !

**Comment by paulijar** [comment]
Okay. When you click a music track in the Music app, the browser is supposed to first fetch an endpoint called `webdav`. Can you see that on the Network tab and does fetching it succeed? That endpoint should return the actual file download link and then the browser should start downloading and playing the file pointed by that link.

Can you see any errors in the nextcloud.log file?

There was once one similar report as this, and in that case the problem was that the reporter had installed a browser plugin "Disable HTML5 Autoplay" to stop pages automatically playing any annoying sounds, but this plugin blocked also playback from the Music app. Is it possible that you have something similar?

**Comment by Telkas** [comment]
So,
Nothing about that in Nextcloud's log.
For html5 autoplay disable, does the File app play the file if activated ?
In the Music app, I've the Webdav request, and in the response, the link is good, but http, not https....
Chrome gives this in the console

> Using sm2 for type audio/mpeg URL http://domain.com/remote.php/webdav/..../file.mp3
> Refused to load media from  http://domain.com/remote.php/webdav/..../file.mp3 because it violates the following Content Security Policy directive: "media-src 'self' blob: data:".
> SM2: sound load error    app.js?v=a05d11d2-15:1752
> Uncaught (in promise) DOMException: Failed to load because  /index.php/apps/music/#/track/6557:1 no supported source was found.
> 
I think the issue come from http request inside https website, perhaps ?

Thanks

**Comment by paulijar** [comment]
> For html5 autoplay disable, does the File app play the file if activated ?

I'm not sure about this but I guess it's possible because starting the playback happens technically a bit differently in Files compared to Music. And a plugin like that cannot really know if the playback is desirable, it has to use some heuristics.

> I think the issue come from http request inside https website, perhaps ?

Yes, this sounds like a plausible explanation. But I don't understand, why would it happen. On my system, the download URL given by the `webdav` endpoint is https as well as the rest of the page. Probably some different configuration somewhere.

**Comment by paulijar** [comment]
> I think the issue come from http request inside https website, perhaps ?

I tested this hypothesis with debugger on Chrome: I inserted a break point just before the URL returned by `webdav` endpoint is used and manually changed https to http. Then I let the code run again and saw similar error messages as you described above. So I think this pretty much confirms that the http/https mismatch is the problem here.

If you are familiar with the debugger and want to try this yourself, you can locate the file `nextcloud/apps/music/js/public/app.js` and put breakpoint on line 688: `var url = result.url + '?requesttoken=' + encodeURIComponent(OC.requestToken);`.

**Comment by Telkas** [comment]
I can do that. But normally i work with assembly....... and chrome or firefox console are so bad

**Comment by paulijar** [comment]
> Can I read the number of tracks/albums/artists with occ command ?

I didn't remember to answer this earlier. There's no such occ command but you can see the number of scanned tracks and albums with mouse hover over the "Albums" and "All tracks" links on the left-hand pane on the Music app UI.

**Comment by Telkas** [comment]
Thank you,
I can see that I've 16500 tracks scanned.
I test the breakpoint on line 688/689, the breakpoint is reached and the result var contain http, not https.
I run Nexcloud with apache2 behind nginx proxy (I need that for onlyoffice integration...).
Normally alls http urls are rewrite in https ... that works manually when I type an url in browser.
Where the music app "read" server Url ?
Another issue, when I click on a letter on the right of the app, there is no effect.
Thanks

**Comment by paulijar** [comment]
> Where the music app "read" server Url ?

The Music app uses interface `IURLGenerator.getAbsoluteUrl` provided by the ownCloud/Nextcloud core to build the URL to the audio file. We just pass in a relative URL and the interface is supposed to return us a working absolute URL. This happens here: https://github.com/owncloud/music/blob/8cb22b45d85388eed8a97b3a1309ff956d544e99/controller/apicontroller.php#L368.

The core seems to implement the interface in file `lib/private/URLGenerator.php`. Looking at the codes there, the logic seems to take the protocol part of the URL from the request which is being handled. So if `/api/file/{fileId}/webdav` is called through https, then also the URL returned by it should begin with 'https'. Why this doens't work for you, is a mystery. If I had to guess, I would say that it has something to do with your apache2/ngingx proxy configuration. Maybe the traffic is secured only up until the first server and then plain http from the proxy to the actual server?

> Another issue, when I click on a letter on the right of the app, there is no effect.

This sounds weird, too, but let's not discuss more than one problem within one issue. Please open a new issue for this.

**Comment by Telkas** [comment]
You are right,
My traffic wasn't crypted between nginx and apache2.
Now that works.
Thanks.

**Comment by paulijar** [comment]
Although the proxy configuration used was untypical, I don't think it was incorrect per se. Hence, I modified the Music app to use relative URLs for playing instead of absolute ones. This is what the Files app was already doing, which is why the playing worked fine in Files but not in Music.
