### ISSUE TITLE
Make it possible to sort items alphabetically in playlists

### ISSUE THREAD

**Issue by benapetr** [owncloud/music#689]
Right now they are sorted by time when I added them to playlist, which makes it very hard for me to find out what is already in list and what is not.

If items were sorted or there was a sort button that would help

**Comment by memen45** [comment]
Would it be possible to also add support for sorting by file last modified time? I prefer having an overview of all songs, ordered by the newest first. Currently only alphabetical order is possible.
Not sure whether I should make a new issue for this or not, since this is not about playlists necessarily, but also the "All tracks" or other views.

I think it would be very nice in general to have sorting options available, e.g.:
 - time added to playlist
 - time added to filesystem (last modified)
 - alphabetically on song name
 - alphabetically on song artist
 - maybe more?

**Comment by strongboy54** [comment]
To add to this, potential for sorting playlists into folders? Similar to how Spotify does it would be good.

**Comment by paulijar** [comment]
Music v1.1.0 now brings the possibility to sort tracks on a playlist according to title, artist, or album. Sorting the "All tracks" view as mentioned by @memen45 is out-of-scope of this issue, and should be requested in its own ticket.
