### ISSUE TITLE
unusual artists ordering with accents

### ISSUE THREAD

**Issue by greku** [owncloud/music#695]
On my setup, I notice strange ordering of the artists.
Basically, I have an artist name "Été 67" and this one is listed completely at the bottom after the ones starting with 'Z'. It would be expected to be listed with artists starting with 'E'.
I believe this is due to the ordering is done with the database, and artists table has collation utf8_bin on my machine.
That said, nextcloud files ordering doesn't show the same issue even though the table collation is the same. I think nextcloud sorts file names with some additional PHP code to avoid this issue.
I think it would be best to adapt the music app code, to do the ordering in the same way as the nextcloud core.
I would expect other people to have noticed the same issue, but haven't found another issue report like this.

**Comment by paulijar** [comment]
Sorry for the delay, I was busy skiing in Lapland :).

Actually, the ordering of the DB is not relevant here. The final ordering of the artists (and albums and tracks) is made on the front-end here: https://github.com/owncloud/music/blob/master/js/app/services/libraryservice.js#L39.

This is actually quite complicated issue because the "right" ordering depends on the culture of the user. For example, a Finnish user expects to find Ä, Ö, and Å in this order after Z. Meanwhile, an English speaking user might expect to find Ä and Å between A and B and Ö between O and P. Or possibly so that, for the sake of ordering, A = Ä = Å. And even the Finnish user expects to find É with or right after E. Incidentally, this "collation" is one of the issues I studied in my MSc thesis more than a decade ago :).

I believe we could utilize [String.localeCompare](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare) to make the sorting more locale-specific. However, it's totally browser implementation-specific, which locale will be used. But I guess that in most cases it will be something which does not surprise the user too much.

**Comment by greku** [comment]
Yes, I studied a bit of Finnish 10 years ago and was in Kuopio for my master thesis.
Indeed, in my case I would rather expect the Ä to be sorted with A. Seems like in German, this would be the most usual way too (but not in Swedish and Finnish). https://en.wikipedia.org/wiki/German_orthography#Sorting
I think it is more universal this way, because for all languages that do not have such accents, it looks more logical, and for a number of important languages that have such accents, it would also be done this way.
If your cloud/browser is setup in Finnish, how does it sort your files in the core?
On my setup, all sorts of accents are ignored for the sorting (sorted as if it was the base letter).

Where is the best place to go skiing in Finnish Lapland? or were you cross-country skiing?

**Comment by paulijar** [comment]
> Yes, I studied a bit of Finnish 10 years ago and was in Kuopio for my master thesis.

Nice :)

> If your cloud/browser is setup in Finnish, how does it sort your files in the core?
On my setup, all sorts of accents are ignored for the sorting (sorted as if it was the base letter).

It works the same on my system, none of the language or locale settings seem to have any effect on the sorting in the Nextcloud Files app. 

Actually, the accents are not completely ignored but they are used as a secondary sorting criteria: if two words are otherwise equivalent but one has accents, then the accented word comes after the unaccented one. So the order would be, for example
AA.txt
AÄ.txt
ÄÄ.txt
AB.txt

My OS is English Win10 with Finnish locale settings. Browsers tested were English Firefox and Finnish Chrome. Nextcloud UI languages tested were English and Finnish.

> Where is the best place to go skiing in Finnish Lapland? or were you cross-country skiing?

I'm not sure about the best but Ylläs is the largest downhill skiing center while Levi is the most popular. Ruka is also very popular but smaller than the two first mentioned. Personally, I was cross-country skiing at Levi. It's a good place for cross-country, too, but Ylläs is probably slightly better in this respect.

**Comment by paulijar** [comment]
> I believe we could utilize String.localeCompare to make the sorting more locale-specific.

I ran a quick test with `String.localeCompare`. This makes at least Chrome use the rules of the browser UI language if no locale is defined by the programmer: With Finnish as UI language, É was ordered with E and ÅÄÖ were ordered after Z. Changing the Chrome language to English (US), the sorting changed so that all the mentioned accented characters were ordered together with their unaccented base variants.

Still, this isn't a quite complete solution yet: having the accented names (sometimes) ordered among the unaccented names would require changes also on how we set up the alphabet navigation anchors.

**Comment by paulijar** [comment]
The alphabet navigation thing was a bit tricky but I think I got it work well now.

**Comment by greku** [comment]
I suppose that you don't want to show exotic letters in the alphabet if not
needed? Actually the hash could be hidden as well if nothing is listed
before A.

**Comment by paulijar** [comment]
I don't know if you checked the implementation, but I'm not actually showing the exotic characters among the alphabet navigation links. Instead, I added a single extra link '…' next to 'Z' which refers to any alphabet coming after 'Z'.

I also considered hiding '#' and '…' when not needed, but in the end, I couldn't convince myself that it would be worth the hassle. Two extra links shouldn't cause too much annoyance, especially because they are quite invisible when they are dimmed in case there is no such scroll target. It's possible I change my mind later, though :D.

**Comment by greku** [comment]
OK. I have seen the changes now. I also tested them. Seems to work well on my setup too. I have some asian characters listed at the end.
I would consider this issue to be solved! :)

Not related to this issue, but another small usability thing that I have is when the window is small, one letter out of two is not displayed in the alphabet. If the remaining letters are the one where I don't have content, it is not possible to use the alphabet links... For example, I don't have X and Z, so no links after V, although I have W Y and ... content. But OK, practically, this can happen if you put your smartphone in landscape mode...

**Comment by paulijar** [comment]
> Not related to this issue, but another small usability thing that I have is when the window is small, one letter out of two is not displayed in the alphabet. If the remaining letters are the one where I don't have content, it is not possible to use the alphabet links... For example, I don't have X and Z, so no links after V, although I have W Y and ... content. But OK, practically, this can happen if you put your smartphone in landscape mode...

Yes, I have noticed that this logic sometimes produces poor results. We could of course try to hide first the unused alphabets, but in generic case, this would not be enough. Then, we would need to hide some other alphabets, too, and the end result could seem a bit random.

One idea I got, was that maybe the alphabets could be shown in two columns which would eliminate the need to hide any. Then again, considering that the main use case for this layout is the landscape phone, having links in two columns would make it very difficult to select the desired link with finger.

One possibility, which I figured out just now, would be to show the links like
A - B
C - D
E - F
G - H
(and so on)

Each line here would be a single link which could be bound to either the first or the second alphabet shown, depending on which one exists in the library.

**Comment by greku** [comment]
> One possibility, which I figured out just now, would be to show the links like
A - B
C - D
E - F
G - H
(and so on)

That is also the most logical solution that came to my mind. If we consider it is especially for landscape smartphone, the extra width it takes should not be a problem. I can try to do this.

**Comment by paulijar** [comment]
The fix is now released in version 0.9.5
