### ISSUE TITLE
count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by soeren-b-c** [owncloud/music#714]
Hi there.

I'm trying out the Music app on my Nextcloud 16.04 with the "Power Ampache" android client.

The client can't load any "artists", and I get a ton of lines like this in my Nextcloud log:

`count(): Parameter must be an array or an object that implements Countable at /var/www/nextnext/apps/music/db/album.php#125	 `

Let me know if you need anything else from me, or if I should try another Ampache client (is there one you recommend?).

Cheers, and thanks for your great work :)

**Comment by paulijar** [comment]
Thanks for the report.

Looking at that referred line `album.php#125`, I can see there is a problem. In case you have albums with no year information AND you are using PHP 7.2 or later, that kind of warning will be printed for each yearless album when fetching the albums via Ampache API.

However, that should be only a warning and fetching the albums should work regardless. Hence, it's possible that the problem in loading artists view on Power Ampache is caused by something else. Or then some server configuration option converts warnings into errors and breaks the execution (?).

Could you try replacing that offending line `album.php#125` with this
`return empty($this->years) ? null : \max($this->years);` ? And then see if it solves the loading problem and if you see anything else in the log.

**Comment by soeren-b-c** [comment]
Hi - thanks for the quick reply.

I tried, and that removed the error from the logs. :)
But still I can't seem to load artists in my client. Albums and the "all tracks" playlist seem to work fine. :(

**Comment by paulijar** [comment]
Okay, that was quite an expected result. But now we have no clue about what is causing the artists loading problem.

As for the question about Ampache clients, Power Ampache is the only somewhat working Android client I have found. On Windows, I have been successfully using Tomahawk.

One way to investigate this could be to create a new account which would have only single audio file. If the problem does not occur with this account, then it would indicate that the problem is triggered by some track/artist. If that would be the case, then the next step would be to add more tracks bunch-by-bunch, until the culprit track is found.

Another way to achieve the same goal would be to configure your music library path so, that only small subset of all your tracks are found by the Music app. But if you have very large amount of tracks, then you might not like all the rescanning involved.

**Comment by soeren-b-c** [comment]
Have tested with just one file - still same problem. The artist shows up under "artists", but when I click the artist, the client just hangs in a loading screen for ever...

Will try to test the client tomorrow with a real Ampache server, to check if it is a client problem.

**Comment by soeren-b-c** [comment]
When trying to connect to a "real" ampache server the client has the same problem, so I'm guessing this is not a owncloud/music issue. I will try to report problem to the Power Ampache project.

How much work would it be to open the Music app up for subsonic clients?

**Comment by paulijar** [comment]
> How much work would it be to open the Music app up for subsonic clients?

In software development, estimating work amounts is always difficult but I anticipate that, for me, it would take at least several days of work. Maybe more than a week to make it perfect, but also partial support of the API could be sufficient for many clients. Someone else could be more efficient, though :). 

There is already the ticket #329 about this feature request. There, one chap volunteered to look into this, but I haven't heard anything after May. So I'm not sure if he's still going to implement it.

Do you think that there would be better selection of client apps for Subsonic API compared to Ampache API?

**Comment by soeren-b-c** [comment]
Speaking from my own experience, all the Ampache clients I have found in the Google Play store have been non-working. Power Ampache I found through F-droid and it kinda works (as you can tell from this bug-report), but not quite...
There are many Subsonic clients in the play store, and the first one I found works fine for me. I assume a lot of the rest do as well...

So my guess would be yes.

Can I ask, are you paid to work on this app, or is it hobby?

**Comment by paulijar** [comment]
For me, this is a hobby project. I have a day job as software engineer but professionally I'm developing totally different kind of software (embedded control SW for diesel engines). Anyways, this means that I can rarely find time to implement any larger new features for the Music app. But sometimes it does happen :).

**Comment by paulijar** [comment]
The warning issue reported here has been resolved and the problem on loading "artists" view in Power Ampache seems to be a client issue. The request on supporting Subsonic API is being tracked in another issue. Hence, there's no need to keep this issue open anymore.

**Comment by dhharris** [comment]
> > How much work would it be to open the Music app up for subsonic clients?
> 
> In software development, estimating work amounts is always difficult but I anticipate that, for me, it would take at least several days of work. Maybe more than a week to make it perfect, but also partial support of the API could be sufficient for many clients. Someone else could be more efficient, though :).
> 
> There is already the ticket #329 about this feature request. There, one chap volunteered to look into this, but I haven't heard anything after May. So I'm not sure if he's still going to implement it.
> 
> Do you think that there would be better selection of client apps for Subsonic API compared to Ampache API?

Unfortunately I haven't had enough time to seriously dive into implementing that feature :(

**Comment by paulijar** [comment]
@dhharris Okay, no problem. I have done some prototyping on this myself during this week, so I may end up implementing this during the coming months. So far, I have managed to deliver some mock-up data to some Subsonic clients but there's still a long way to go.
