### ISSUE TITLE
Any iOS Apps

### ISSUE THREAD

**Issue by talkinggoat** [owncloud/music#724]
I would like to use the Subsonic interface for Music, but none of the iOS apps seem to work. Some of them show the artists and albums, but they don't show the tracks or play anything. Some show nothing at all. Is there a solution?

**Comment by paulijar** [comment]
You mean the Subsonic interface? I have no iOS device to test with, so I don't know. But there is a long list of Subsonic compatible iOS apps at http://www.subsonic.org/pages/apps.jsp, and I would have guessed that some of them would work together with the Music app.

Also, I have been working to make the Subsonic API support more extensive since the release 0.11.0. There is a chance, that some clients not working with 0.11.0 would work with the current development version and the upcoming release.

**Comment by talkinggoat** [comment]
Yes, sorry, Subsonic. IDK where I got soundcloud. 

I have tested Soundwaves, iSub and substreamer. They either don't work at all or load the playlist, but not the actual music. They DO work on Ampache proper, though. 

I'll go through the apps on Subsonic's website for you and see if I can get them to work on my iPhone.

**Comment by talkinggoat** [comment]
Key:
ampache/music/name/status

✅ ❌ iSub
❓ ❌ Audiophone (discontinued)
❓ ❌ Z-subsonic (discontinued)
❓ ❌ SubStream (discontinued)
✅ ❌ SubStreamer
❓ ❌ SubHub (discontinued)
❓ ❓ AvSub (paid)
✅ ❌ SoundWaves
❓ ❓ play:Sub (paid)

Ampache 3.9
Music 0.11.0

**Comment by paulijar** [comment]
The Music app v0.11.1 was just released. There is a chance that it would fix the compatibility with some of the iOS clients. However, if the case was such that the client app otherwise worked but could not play any music, then the situation most likely is still the same. Such client app is probably depending on the [Subsonic HLS API method](http://www.subsonic.org/pages/api.jsp#hls) to stream the music, and that's something we are still not supporting.

**Comment by MichaelBechHansen** [comment]
play:Sub (https://apps.apple.com/us/app/play-sub-subsonic-music-streamer/id955329386#?platform=iphone) relies heavily on the JSON-response format from the Subsonic API, and is thus blocked by https://github.com/owncloud/music/issues/730

**Comment by mmccarn** [comment]
[Soundwaves](https://apps.apple.com/us/app/soundwaves/id736139596) by Simone Tellini is working for me with only one caveat - Music collections get broken up.

For example - I have 'Jesus Christ Superstar' in my music folders.  The only way I could play the two albums in order was to manually create a playlist for each.  Artist View gives you only the list of songs by each singer, and folder view plays the songs alphabetically instead of in track order.

The app has an optional 'paid mode' to disable ads -- but I don't get any ads and I haven't paid anything (I'm currently running v2.8 of the app).

**Comment by paulijar** [comment]
I still have no first-hand experience on any iOS clients, but as others have commented it, I believe that at least Soundwaves and play:Sub can nowadays be used with the Music app. If anyone knows of any other alternatives, feel free to add those to the wiki page https://github.com/owncloud/music/wiki/Subsonic or https://github.com/owncloud/music/wiki/Ampache.

I see no reason to keep this issue open any longer.
