### ISSUE TITLE
Subsonic can navigate outside of the Music folder

### ISSUE THREAD

**Issue by JoshuaPettus** [owncloud/music#725]
Hi,
I'm using Nextcloud 17.0.1 with Subsonic 4.4 on Android

I noticed that when I set subsonic to folder search in the library, it is very possible to navigate outside of the Music folder to see the rest of my directories on the nextcloud server.  Granted it can only play music files but this doesn't seem ideal, security wise, especially with subsonic's password system.  Is there a way to lock it down to just the specified music folder on the server?

Thank-you!

**Comment by paulijar** [comment]
Hello,

On the web UI, you have the setting "Path to your music collection". By default, it's your home directory root, but it's recommended to select your actual music folder. Then, only that folder and its subfolders are shown on Subsonic clients.
![image](https://user-images.githubusercontent.com/8565946/69269300-60ea5480-0bd9-11ea-903d-06145a902b26.png)

However, your question made me think and I realized there is loop-hole there: If you know/guess/brute-force the folder IDs, you still can fabricate the Subsonic API calls manually to see the names of *folders* outside the configured music path. One cannot get names or contents of any other *files* except the scanned music files, though. But still, this is a potential breach in confidentiality, and I'll considered it to be a high-priority issue to fix. I'll publish a fix release within a couple of days.

**Comment by JoshuaPettus** [comment]
My path to my music collection is set to /Music/ hence why I opened the ticket.  When I opened the folder view in subsonic, It started in /Music/ but was able to go back one directory to /.  No brute force required. It really shouldn't be possible for it to be aware of other than the music directory I set.  But maybe your new patch will fix that anyway.

**Comment by paulijar** [comment]
Ok, thanks for the clarification.

So I actually had another oversight there: I didn't realize that when fetching folder listing via Subsonic API, there is always also the parent folder ID included. And this parent folder ID may point to outside your configured music path. Another thing, I hadn't noticed, was that the Subsonic Android app actually uses this parent folder ID for navigation when you tap the arrow icon on the upper left corner of the screen. If, instead, you use the "Back" button of your phone to navigate back, then the navigation happens via the local view stack. This is what I have been mostly doing, and hence I hadn't noticed the issue.

My previous fix already prevents the navigation outside the configured music folder also in this case, but it is a bit rough on edges: trying to navigate back to the root level using the top-left arrow button now shows an error note to the user. This problem actually happens also when browsing by artists (rather than folders), and here it has probably happened already previously.

**Comment by JoshuaPettus** [comment]
Awesome!  I have to say, this is easily my most used app in nextcloud. Instant availability of my entire music library, everywhere, has been such a great thing.  Thank-you, for all your hard work!

**Comment by paulijar** [comment]
The new release v0.11.1 including these two fixes is not out!

Thanks also for reporting this, it was much appreciated. I probably wouldn't have noticed the issue on my own at least for a long time.

**Comment by JoshuaPettus** [comment]
Glad I could help! The update was just pushed to nextcloud update, so I just gave it a try myself.  Works perfectly!  

Thanks!
