### ISSUE TITLE
Handling huge libraries 

### ISSUE THREAD

**Issue by wjg57** [owncloud/music#728]
I've a centrally managed collection of approx 70'000 music files and the music plugin completely fails to handle that amount of data:
* Scanning takes 4ever. it can neither be interrupted once started nor can the "new music available" popup be moved or removed or backgrounded.
* Trying to show an album starting with "z" is completely impossible, as music tries to load all the albums inbetween...
* The library is structured alphabetically by artist, so if there were a way to re-use the existing structure in music, e.g. by having multiple libraries instead of just one or having a hierarchical structure for navigation, it would improve things a lot.

**Comment by paulijar** [comment]
Yes, it is a known fact that the application design does not scale well for huge libraries. Firefox on desktop is the only browser which has even a chance of remaining usable with tens of thousands of tracks but 70k might be too much even for it. For Chrome and Edge, exceeding 10k tracks could already be too much for comfortable use.

It's difficult to do anything for the scanning speed, except possibly offer an alternative mode where file metadata is not read and all the artist and album names are guessed from the file/folder names. It would probably make sense to collapse the "new music available"/"scanning..." popup to the bottom of the screen when there are already albums shown.

It would be possible to use some kind of "virtual scrolling" method to load the library content on demand rather than load everything immediately. One of the difficulties on those is, that they may easily make the scrolling feel less fluent for those users who have "normal" sized collections. I would bet that quite small portion of the users have 70k+ tracks in their library (or even more than 10k), and we need to be careful not to screw the majority to serve a small minority. But still, you are not the only one with this problem. I have read similar reports before, and one user even mentioned a collection of 150k tracks.

**Comment by JoshuaPettus** [comment]
I'm just the peanut gallery, but wouldn't the answer to only use this behavior when the library exceeds 10k songs, otherwise stick with the standard behavior?

**Comment by paulijar** [comment]
@JoshuaPettus Yes, that would be an option. If the virtual scrolling is ever implemented, I may considered something like that. The downside of this approach is that it essentially creates two parallel view layers which might need to be constructed quite differently. Afterwards, when we want to add any new UI feature, it will always require double work.

**Comment by paulijar** [comment]
@wjg57 Music app v0.12.0 with significant performance improvements for huge libraries was just released. Also, the "New music available"/"Scanning" popup now uses a less obstructive layout.

I realize that the scanning of 70k tracks still takes ages, and the UI design is still not very well suited for such large collections. But overall, the app should now be much less painful to use with huge collections. If you can give the new version a try, I would be interested to hear your feedback.

**Comment by RobertZenz** [comment]
> It would be possible to use some kind of "virtual scrolling" method to load the library content on demand rather than load everything immediately.

Is paging an option? I mean, only displaying the albums of the current letter would for sure improve things in this regard. It would change the user experience, but would be better than being unusable.

Additionally maybe giving the option to *not* display the album art would also be a possibility, as loading these also takes long.

**Comment by paulijar** [comment]
@RobertZenz Pagination is another option, which could make sense for huge libraries, but would make UX less fluent for the "normal sized" libraries. Again, it would be possible to set some library size limit, where we would switch to another UI style, but then we would have two different UI architectures to maintain. So this wouldn't be my first choice.

Have you tested the v0.12.1 and how large is your library? This version employs kind of "light version" of virtual-scrolling, or rather, lazy-loading. It doesn't make the UI completely immune to the size of the library, but it should improve the scalability a lot without interfering too much with the UX of the small to normal sized libraries. I believe the app should now remain rather usable with at least 10´000 albums, and it shouldn't matter if each album has 1 or 100 tracks.

Also, the album covers are lazy-loaded on v0.12.1 so that each cover is loaded when it first time enters the view-port. If it just quickly passes through the view-port, like when you navigate from the top of thew to artists starting with "Z", then it is not loaded.

**Comment by RobertZenz** [comment]
Yes, the 0.12.1 update was quite an improvement for me.

**Comment by paulijar** [comment]
Music v0.13.0 was just released and it brings some further improvements for huge collections: Also the 'All tracks' view should now work fluently with tens of thousands of tracks. Furthermore, there is now a search/filtering feature, which should be rather useful to find your desired tracks and albums from a huge collection.

I think that the support for huge libraries has now improved so much, that we can close this issue. Of course, there's always room for improvement, but it's kind of pointless to keep this kind of issue open forever.
