### ISSUE TITLE
Background mode

### ISSUE THREAD

**Issue by kr3t3n** [owncloud/music#731]
Hi, love the app, works perfectly for me.

This is more of a feature request than an issue but do you think you can add the ability to continue playing the music in the background while user navigates in other sections of NextCloud? Ideally, it would also show a small window with the current song and artist, maybe a small thumbnail and a play/pause button, hovering somewhere in the window.

**Comment by paulijar** [comment]
Thanks for the feedback.

I believe that implementing this feature would be somewhere between difficult and impossible. This is because the architecture of Nextcloud is not really designed with this sort of use cases in mind. Each application is basically a stand-alone web page, and there's no way to continue running parts of one application when another application is opened.

At the same time, you can kind of achieve the same thing by pinning the Music app to one tab on your web browser, and using another tab to navigate to other Nextcloud views. This makes it even less tempting to invest the scarce development resources on investigating the options to implement this feature.

**Comment by kr3t3n** [comment]
Thanks for the swift reply. I completely understand the logic and agree that pinning the tab works just fine, it's more about keeping less tabs. I hoped there would be a way to plug into Nextcloud's "footer/header" global sections (if they are truly open for plugging into resources). 

Anyway, I do just fine, my request was always for an unessential feature anyway.

Happy holidays!
