### ISSUE TITLE
Quality of scaled album covers is rather bad.

### ISSUE THREAD

**Issue by RobertZenz** [owncloud/music#734]
As far as I can tell, the cover images of the albums are being scaled down, which is a very good thing as it means faster loading time. However, the quality of these scaled images is rather bad.

Take this example:
![6d970ca9ca78f7a8b4053c02a1dd16a4](https://user-images.githubusercontent.com/611377/72347176-d2291e00-36d7-11ea-9678-bd1ae1990366.jpeg)
![cover](https://user-images.githubusercontent.com/611377/72347200-de14e000-36d7-11ea-8ecc-f33f686d74d6.jpeg)

I'm using v0.12.1 currently.

**Comment by RobertZenz** [comment]
Additionally, at least on my instance, the covers are scaled to 200px in size but the GUI always displays them at 190px, which is leading to further artifacts.

**Comment by paulijar** [comment]
You are right, we are probably shrinking the images more than what would be necessary. Especially now when the newest versions of the app load the album covers on demand rather than loading them all at once.

Your example cover is rather challenging because of the thin font used in the text. But when scaled to 380px, it already looks quite okay:
![album_cover_380px](https://user-images.githubusercontent.com/8565946/72669872-caeb7280-3a3f-11ea-9a51-504adf635350.jpg)

With the original 200px size, the image size is some 8.5 KB, and with the 380px size, it is about 20 KB. This is still reasonable, so I think this could be a good compromise. 380px also scales nicely to 190px element, although this might not be all that important: many users will anyway have enabled the UI scaling in their OS or zooming in their browser, and the size of one logical pixel is not the same as one pixel on their screen.

I also tested increasing the "jpeg quality" setting used when saving the shrunk down image. It is currently 75% and I tested 100%, but this made no visible difference at least on your example image. However, the size of the image grew significantly. I didn't actually test this on the 380px image, but on a 300px image the size quadrupled from 15 KB to 60 KB. That is, this is clearly not worth it.

**Comment by RobertZenz** [comment]
No, that one still looks bad and increasing the size does not help at all (as it leaves the problem at the doorstep of the browser). Look at the text and how jagged it is, compare that with these two images which were created with the default settings of imagemagick:

![test-380](https://user-images.githubusercontent.com/611377/72675828-64d80d00-3a8a-11ea-8045-6f68d55a0978.jpeg)

![test-200](https://user-images.githubusercontent.com/611377/72675829-6570a380-3a8a-11ea-82c7-c84859617f38.jpeg)

Do you notice how well preserved the text is in these ones?

If I see this right [you're using the imagescale function of php](https://www.php.net/manual/en/function.imagescale.php), unfortunately there is no documentation on how this one works, but I guess that it was custom implemented by the PHP guys (which would explain why it sucks so bad at resizing images). It would be better if you'd test whether imagemagick is available, and if yes, use that instead as it produces far better output. I know that quite big parts of NextCloud already using imagemagick when it is available but I do not know whether they are exposing an API for that.

**Comment by RobertZenz** [comment]
Another alternative seems to be [`imagecopyresampled`](https://www.php.net/manual/en/function.imagecopyresampled.php) which *seems* to produce better output than `imagescale`. However, I'd still advise towards imagemagick if it is available.

**Comment by paulijar** [comment]
Thanks for the feedback.

I did some testing, and I think that `imagecopyresampled` wins the price here. This is its output:
![imagecopyresampled_380](https://user-images.githubusercontent.com/8565946/72684011-831f2680-3ae5-11ea-945d-88a4c816396a.jpg)

The text is preserved about as well as with Imagick. The original colors of the image are not preserved quite as well, but on the other hand, the image file size is seriously smaller than with Imagick: the size of this file is 18 KB, while your 380px Imagick example is 132 KB. Setting the compression ratio to 75% on Imagick reduces the file size, but it is still 56 KB. Lowering it further to 50% still gives file size of 50 KB, but then compression artifacts are clearly visible. Even the 200px/75% image created with Imagick is still sized at 42 KB.

**Comment by RobertZenz** [comment]
Yeah, looking better. It's quite duller, you're right there, but I guess that's a certain trade-off.

**Comment by RobertZenz** [comment]
As a side note, you might want to put the size of the generated thumbnail into a setting, to allow the admins to adjust it depending on their targets.

**Comment by paulijar** [comment]
> As a side note, you might want to put the size of the generated thumbnail into a setting, to allow the admins to adjust it depending on their targets.

Yes, that would be possible. But on the other hand, the Music app has currently no admin settings, only the user settings. And this is quite technical detail to be put into user settings. 

Note also, that the shrunk down cover images are cached on the server, and the same cached images may be used in the Subsonic and Android APIs. There, the client app may present the image in much larger size than the web UI does. Hence, the extra size may be useful even if the web page is never used with more than 100% scaling.

**Comment by RobertZenz** [comment]
> Yes, that would be possible. But on the other hand, the Music app has currently no admin settings, only the user settings. And this is quite technical detail to be put into user settings.

Sorry, I should have been more clear, I was thinking about the config.php file. I agree that this is a very technical detail, so it would make sense to have it in the config.php.

 >  Hence, the extra size may be useful even if the web page is never used with more than 100% scaling.

Agreed there.

**Comment by paulijar** [comment]
> I was thinking about the config.php file.

Yes, this makes more sense. I hadn't used the config.php before for the settings of the Music app. But it turned out to be easy, so I just added this. The config key to be used is `music.cover_size`.

If you ever want to play with this, note that you need to clear the cover cache for the changes to take effect (this happens also automatically whenever a new released version of the app is installed):
`occ music:reset-cache <username>`
or
`occ music:reset-cache --all`

**Comment by RobertZenz** [comment]
That's very good to know, thanks.

**Comment by paulijar** [comment]
Music app v0.13.0 including this enhancement was just released.
