### ISSUE TITLE
can't install music, due to php 7.4

### ISSUE THREAD

**Issue by maxwell-public** [owncloud/music#738]
Error "PHP with a version lower than 7.3 is required." prevents installing Music. Please upgrade requirements

**Comment by dasunsrule32** [comment]
Same issue here. 👍

**Comment by paulijar** [comment]
The development version in the master branch already declares support for PHP 7.4, which should solve this issue. However, I've had some problems setting up a test environment with PHP 7.4, and I'm not sure when will I have time to solve those. If someone with PHP 7.4 is able to test the development version of the Music app, then please share your results here.

**Comment by paulijar** [comment]
I now managed to set up a test environment for PHP 7.4, and the Music app seemed to work fine on it. For the record, our version of getID3 library had to be updated to reach the PHP 7.4 compatibility, but otherwise, no code changes were needed.

Music app version 0.13.0 was just released, along with the support for PHP 7.4.
