### ISSUE TITLE
Hierarchical folder view : enhancement request

### ISSUE THREAD

**Issue by gessel** [owncloud/music#742]
Some of us sort our music into folders by genre, etc.  It'd be nice to be able to navigate using this native view - the "folder view" shows only the terminal containing folder, not the hierarchy :(.   One might use it, for example, to limit the list of files to a manageable count, improving UX performance.

It also makes navigation easier for those of us used to the structure.

It would be useful for creating playlists from the folder structure.

An alternative/additional feature might be to add an "action" in the Files app to "add to playlist..."  Either a song or the recursive contents of a folder, likely not too different from adding the "preview" -> play function works now.

**Comment by tiggerfan** [comment]
I'd also like to see this feature.  I've 15,000+ songs,  1200+ albums (folders) and already have them on a linux file server with a folder/directory hierarchy so i can quickly find things.  trying to navigate this many in nextcoud gui creating  playlists isn't worth the time and pain.  cheers.

**Comment by TtuxX** [comment]
Yes, changing this would really be great ! 

The "Folder" section on the sidebar is counter-intuitive to me, I would ideally wish the "Folder" section to preserve folders structure and hierarchy to list folders (where musics are detected) just like the Nextcloud Files app does list folders :)

**Comment by TtuxX** [comment]
Thank you very much @paulijar, this view is great !! :)

I have 2 feedbacks/questions regarding this very nice new tree layout:

**1. I'm getting duplicate folders:** 

It appears that the folders names are duplicated according to the number of subfolders they contain (and only the last folder occurence actually shows the folder's content).

Screenshot:
<img width="911" alt="image" src="https://user-images.githubusercontent.com/6570830/136771530-3ccce3bd-c980-44b6-9bd0-6fbe3a381295.png">

**2. Would it be possible to implement switches for date an name sorting in this view, a bit like Nextcloud files app ?**

I know it might sound particular but just like I sort everything on my server by date, I do also dowload my musics in a sequential manner and bind memories to them. 
Sorting them by date would allow me to scroll sequentially through musics, thus memories :) 

Thank you so much Pauli for your great work on this app !

**Comment by etyrnal** [comment]
"I know it might sound particular but just like I sort everything on my server by date, I do also dowload my musics in a sequential manner **_and bind memories to them_**."

i've been trying to explain this to devs for a long time.  This very idea.  To be able to sort all tracks by the date you added them, so for example, i can go back to December and see the music i added when the kids cam to visit, or that song i added last month which i cannot remember the name.  Imagine trying to find that song in a collection of 25K tracks -- digging through folder hierarchies?  Yikes!  But in music apps/UIs where you can sort all tracks by date received?  I can ALWAYS find it that way, because i will remember it by the associated songs listed before and after it, etc.

I wish they'd do this in airsonic too!  I've started using the nc Music app because i cannot do it in airsonic.

My music collection in my airsonic server spans 4 hdds across three machines.  So, it's nice when the database in a music app acts like one.  It's a shame to over simplify a music interface.

**Comment by paulijar** [comment]
@TtuxX 
1. This is clearly a bug. I extracted it to a new issue https://github.com/owncloud/music/issues/905

2. Listing tracks by date added is already tracked at https://github.com/owncloud/music/issues/903. But I doubt it that this would be added to the Folders view. In the mentioned issue, it's discussed that it could be added to the *All tracks* view, but another option would be to have a totally new view; it could then be like the Genres view but with dates as the separators.
