### ISSUE TITLE
Enhancement request: List artist for albums by various artists as 'Various Artists' or just the Album name 

### ISSUE THREAD

**Issue by dddddddavid** [owncloud/music#745]
I have several compilation albums. I can't listen to the entire album without creating a playlist as the tracks are scattered across the interface under the name of each individual artist.

This also clutters up the page as a new entry, complete with thumbnail is created for each track
Example:

![Screenshot from 2020-03-05 13 24 12](https://user-images.githubusercontent.com/57491766/75985792-d4904300-5ee4-11ea-93f1-1e93a04b55d2.png)

It's also a problem if an album by one artist contains a track where they collaborate with another artist. 

Would it be possible to have the artist presenting as 'Various Artists' or the ability to set the artist for an entire album?

Hope that makes sense

**Comment by paulijar** [comment]
Yes, it is possible. You just need to set the *Album artist* tag for each track belonging to a compilation album. Then, this tag will be used for sorting instead of the *Track artist* tag, which should contain the actual performing artist.

On the following screenshot, I have set the *Album artist* for the compilation albums as "Eri esittäjiä". That's Finnish for "Various artists". You can see, how the track artists are then shown next to the track names with dimmed font.
![image](https://user-images.githubusercontent.com/8565946/76019295-25765a80-5f2a-11ea-8ba4-9112e35f1968.png)

**Comment by paulijar** [comment]
Closing because the requested feature is already available.
