### ISSUE TITLE
Subsonic API call getLicense() returns 'never', which is invalid according to spec

### ISSUE THREAD

**Issue by jheyens** [owncloud/music#759]
Subsonic API call getLicense() returns 'never' in field 'date', but, according to the API specification 'date' must be of type 'xs:dateTime', for which 'never' is [not a valid value](https://www.w3schools.com/XML/schema_dtypes_date.asp). Also, it does not matter that the 'date' field is optional.
A client implementing the spec may fail to parse this (which, incidentally, UltraSonic does)

I think since we cannot specify a reasonable value here, no value should be set at all. If you think this causes issues with existing (non-conforming-) clients, I'ld suggest something like $today+5 years, so we'll only see issues regarding this starting with 2033 :-)

**Comment by paulijar** [comment]
Thanks for the report. This API endpoint has been like this since my first draft of supporting the Subsonic API, and I suspect that none of the tested clients has ever used this method :D. At least I haven't seen the license information visible on any UI. I shall remove the optional fields from the response.

**Comment by paulijar** [comment]
This fix has now been released in the Music app v0.14.1. UltraSonic 2.7.0 seems to work fine now with the Music app. Thanks again @jheyens for your reports, much appreciated.
