### ISSUE TITLE
unknown artist in library / Scan specified folder

### ISSUE THREAD

**Issue by powerlocke-ctrl** [owncloud/music#771]
Hi there! 
My Music collection has around 73000 files, which are stored in a seperate SMB Share.
Since a few weeks i'am trying to reduce files with "unknown artist"
Actually are 34000 files with unknown artist. At start there were more than 42000 files. 
I tried occ music:scan User --rescan
This reduces number of files with every new scan. 
Unfortunately scan aborts after a lot of hours. 

If I click the Info-Button next to file, all information from files are correct. 

I have resetted whole database and started a new scan, but the number hasn't been reduced. 

Now I would to add an specified folder to scan, like occ:scan --path/User/Artist/Album1
But such commans are not working. 

I tried also to add argument --clean-obsolete, but this does not reduce files. 

My Nextcloud v19.0.0 is installed on a Synology NAS, PHP 7.3.16. I use mySql v. 10.3.21

Has anyone other ideas?

**Comment by paulijar** [comment]
Thanks for the report.

Those SMB shares are tricky and similar problems have been reported before in #670. There are many moving parts here, but one thing is that you should make sure that you have `libsmbclient-php` installed.

I find it rather odd, however, if you can see the artist name correctly behind the 'info' button although it has not been scanned correctly. Pressing the info button extracts the metadata of the file basically the same way as the scanning process does. So it seems, that at the time of scanning the metadata reading has failed but now it succeeds.

The `--clean-obsolete` option doesn't help here, because all it does is, that it browses through all previously scanned files and removes those which are no longer available. Usually there should be no "stray references" like this, but under some special circumstances, it is possible. It also takes quite much time on large collection, so that's why it is not done by default.

**Comment by powerlocke-ctrl** [comment]
I've checked via phpinfo.php and it seems like libsmbclient-php  is not installed. 
And I cant't find a tutorial how to do it on Synolgy NAS :-(

**Comment by paulijar** [comment]
Wait, are you running Nextcloud directly on your Synology NAS server? But you still have set up Nextcloud to use the files via SMB, even though those files reside on the same device with the Nextcloud instance? Or do you have another SMB server, which is accessed over the network by the NAS?

**Comment by powerlocke-ctrl** [comment]
Hey, 
yes. I've installed on my DS918 Nextcloud.
A second NAS is connected as external storage (SMB) to my Nextcloud. 

After connect SMB to NC I run occ files.scan, thereafter occ music:scan. Last I am repeating very regulary to reduce number of files with "unknown artist". But this aborts often.

**Comment by paulijar** [comment]
Okay. Would it be an option to install another Nextcloud instance on the second NAS, and use the sharing capabilities of Nextcloud to access those files from your DS918? That would work around using the problematic SMB external storage support.

**Comment by powerlocke-ctrl** [comment]
Hi Pauljar, 

I've tried to this. No chance. 
I created a second NC and gave the shared SMB collection via federated cloud to new one. 
Via files I can see and open files, but it is not possible to set the new share as music folder in the music app.

**Comment by paulijar** [comment]
Okay, that's unfortunate. It seems that the federated sharing isn't working as well as I was hoping for. I think that I have had at least somewhat better success with it earlier, but I'm no longer certain. It was some years ago when I previously tested it.

I now did some more testing on the federated shares. In my test setup, I shared a folder with 13 audio files from a Nextcloud 18 instance with a Nextcloud 19-beta instance. Both resided on the same server, but I was using them through two different domain names (both routed to the same IP). On my test, I actually couldn't browse the shared folder via Files (opening the folder was loading until timeout), but it was possible to set it as my music library root. But then, the scanning took a lot of time and generated a truck load of errors to nextcloud.log. These errors made it clear, that the federated share had the same problem with `fseek` that is affecting the external SMB storages when `libsmbclient-php` is not available. Also, the Albums view of the Music app never loaded (maybe because extracting the cover images from audio files failed?), but other views did show the files from the federated share. None of the tracks could be played, though. So all in all, this setup was not usable for any practical purpose.

I guess, that it is then impossible to extract the file metadata in a setup like yours. What we maybe could do, would be to offer an option to skip the metadata extraction, and build the music index based on the filesystem structure only. The app would then probably assume directory hierarchy like `artist`/`album`/`track_name.mp3`.

**Comment by powerlocke-ctrl** [comment]
Hmm. Maybe your suggestion could be an option. 

Do you see any chance, that I can specify a folder, which I want to scan. I want to try to reduce the files step by step for each folder. 
When I start a scan as usual, it beginns always with same track. And because the scan stops after a while I think I can be able to reduce "unkown artist" a little bit easier. 
If now a file at the end of scan list is unknown... maybe the scan never reach its end because it stops anywhen. 
In track information I see artist, album and title. So I know its path an would start to scan only this folder...?

**Comment by paulijar** [comment]
> Do you see any chance, that I can specify a folder, which I want to scan.

Yes, this kind of option would make sense now, as we have the `--rescan` option (it was just added a couple of releases ago). I'll look into this when I have time.

**Comment by paulijar** [comment]
I just released Music app v0.15.1 and included there a new option `--folder=<target>` for the `occ music:scan` command.

**Comment by powerlocke-ctrl** [comment]
Hey. Thanks for adding this Option.
Actually I am not Home, I can test it within the next 14 days.
I'll give a feedback.

**Comment by powerlocke-ctrl** [comment]
Short feedback after a few days. 
For me it is now possible to reduce the file and add them correctly in my list. 

But I don't know why, I had now two times, all my files have been disapperead. 
Just a few minutes ago again. Now I deleted complete database in myphpadmin. 
Now I beginn a new file-scan with occ files:scan. I would be happy, if scan from occ music:scan would be nearly as fast as files:scan. 
For my collection with around 70.000 files I need around 5 days and thereafter I have to reduces unknown artist files.

**Comment by paulijar** [comment]
Thanks for the feedback.

When you say your files have disappeared, you mean they vanished totally from Nextcloud? Or only from the Music app?

> I would be happy, if scan from occ music:scan would be nearly as fast as files:scan

The difference here is that `files:scan` only needs to browse through the directory hierarchy, storing things like file name, creation date, and size. All of these are maintained in the file system. Meanwhile, `music:scan` has to open each of the files to read the metadata. As you are using the SMB storage backend without `libsmbclient-php`, this operation consumes a lot of time. I'm not certain, but I suspect that it may even transfer the whole file from SMB to your Nextcloud server just to read the few kilobytes of metadata.

In situations like this, it might be preferable to have an option to skip the metadata extraction, and rely solely on the file and folder names (as mentioned earlier). This would of course come with the cost of not being able to show e.g. the genres and release years of your tracks.

**Comment by paulijar** [comment]
Several issues have been discussed within this ticket but I believe that the only open one is the idea that there could be an alternative scanning mode which wouldn't extract the metadata of the files. I now created a new issue https://github.com/owncloud/music/issues/914 for this feature, and this old issue can be closed.
