### ISSUE TITLE
"Notification" view broken when accessed in Music

### ISSUE THREAD

**Issue by pilsnerbeer** [owncloud/music#772]
In Music (but nowhere else), accessing the notification area in NC doesn't work, instead a long shape rectangle is rendered:

![Screenshot_1](https://user-images.githubusercontent.com/36133540/85797623-49111b00-b73c-11ea-8234-bd37d29ad161.png)

This is expected behavior:

![Screenshot_2](https://user-images.githubusercontent.com/36133540/85797655-5928fa80-b73c-11ea-99a1-64ef78594e85.png)

NC 19snap with Music 0.14.1

**Comment by paulijar** [comment]
Thanks for the report.

This seems to be the case only when there are no notifications. When there are any notifications, they show up fine. The problem seems to be, that the width of the "No notifications" placeholder gets set incorrectly to a very large value. I didn't look at it closer, yet, but I guess that one of the style definitions intended to be used with the Music app UI elements is now accidentally applied also on this element.

**Comment by paulijar** [comment]
This has been fixed in the Music app release v0.15.0.
