### ISSUE TITLE
Lyrics line formatting

### ISSUE THREAD

**Issue by britzke** [owncloud/music#780]
I have imported a mp3 file with included lyrics, which has been added in iTunes. Alle the line ends seem to be gone. This may Be an html formatting issue, when rendering lyrics out off the mp3 file itself.

**Comment by britzke** [comment]
Sorry, it should be "Lyrics line formatting" in the headline.

**Comment by paulijar** [comment]
Thanks for the report. Could you share one such file with me? You can find my email address from my profile. Which browser are you using?

**Comment by britzke** [comment]
I verified the issue  with Safari, Firefox (OS X) and Edge (OS X, Beta) in their newest version.

**Comment by paulijar** [comment]
Your file seems to use "CR only" style for line breaks. This is kind of weird, because no modern systems should use this style. It used to be used on the classic Mac OS, but after OSX, also Mac should be using "LF only" style like the other Unix-based systems.

The web standards do not support this kind of line breaks, so this is why it gets rendered incorrectly. I shall see, if I could convert such lyrics automatically to more compliant format.

**Comment by paulijar** [comment]
The Music v0.16.0 was just released, including also a fix for this issue.
