### ISSUE TITLE
nextcloud 20 support

### ISSUE THREAD

**Issue by JoshuaPettus** [owncloud/music#790]
Something broke with nc20.  When you open the app you get

No search results in this view for {{ querryString }}

**Comment by paulijar** [comment]
Yep, I just downloaded the NC20 RC today myself. This is related to the new global search which conflicts with Music's own search implementation. I'll try to fix this in the near future. I may need to disable the Music's search on NC20 as a temporary solution if I don't immediately find a better alternative.

**Comment by JoshuaPettus** [comment]
did the internal search have any features the global doesn't?  if not maybe turning it off for NC20 might be for the best?

**Comment by paulijar** [comment]
The global search won't find any results from the Music app before I provide a new plugin for the search system. And the internal search of the Music app has been pretty nifty, with the ability to combine keywords found from several fields of the artist/album/track, and basically lightning fast results as long as the library is not humongous (and even then, the delay is acceptable). I doubt it that as good UX is possible with the global system even if I provide the needed plugin for it.

**Comment by edouda** [comment]
> Something broke with nc20. When you open the app you get
> 
> No search results in this view for {{ querryString }}

Same problems. Thanks for having noticed it !

**Comment by paulijar** [comment]
In addition to the search issue mentioned above, there is some problem related to the loading order of the components. Even when the search is disabled, the loading of the page sometimes fails. Reloading the page may solve the issue, but sometimes it doesn't. Strategically placed break point can be used to prevent the problem, so clearly this is some timing issue. Maybe this has something to do with the updated jQuery version shipped with NC20, but I don't know. I'll try to investigate this more this weekend.

**Comment by JoshuaPettus** [comment]
Hey thanks! Thankfully the subsonic component still works, and I can use the commandline to rescan if I have too :)

**Comment by psklb** [comment]
Hi, same issue here &  the refresh button doesn't work
Manual scan with occ seems to work (no error msg) but in the list of songs, new songs doesn't appear so it is impossible to modify playlists. 
Thank you for your work an support.

**Comment by paulijar** [comment]
Took me whole weekend to put the Music app into webpack as is now recommended by Nextcloud. Yesterday, I managed to properly bundle in an own version of jQuery to the same webpack, and I *think* this solved the loading issues. There are still some side-effects from using another jQuery instance which I need to sort out before I can make an NC20-compatible release. But now there shouldn't be any big obstacles left, so I'm much more confident that the release can be made soon.
> 
> 
> Even when the search is disabled, the loading of the page sometimes fails. Reloading the page may solve the issue, but sometimes it doesn't. Strategically placed break point can be used to prevent the problem, so clearly this is some timing issue. Maybe this has something to do with the updated jQuery version shipped with NC20, but I don't know. I'll try to investigate this more this weekend.

**Comment by psklb** [comment]
Thank you for the work. I will upgrade as soon as you release the NC20 version.
I really love your app because I use it in my music band : having uploaded every songs we use to play, i create one playlist for every set we play (it change every date). therefore, every musicians can, without any effort, repeat the set in the right order, using the subsonic player they prefer. 
best regards

**Comment by paulijar** [comment]
The Music app version 0.17.0 with support for NC20 is now out!

I managed to make also the search work again within the Music app. There is still such problem, that if you enable the debug logging, you will get lots of lines with the message "/appinfo/app.php is deprecated, use \OCP\AppFramework\Bootstrap\IBootstrap on the application class instead.". This, however, shouldn't cause any other harm for now, and I didn't want to postpone the release any longer to investigate this.

Taking the webpack into use on the front-end was rather large architectural change. As part of this change, many vendor libraries were also updated to newer versions. I fixed quite a few subtle issues caused by these changes but it is well possible that some bugs were still left hiding. Please report if you notice anything off.

**Comment by JoshuaPettus** [comment]
Awesome! Fantastic, will let you know if anything is stragne.

**Comment by psklb** [comment]
Thank you ! Everything is fine now for me !
