### ISSUE TITLE
Music app broken in ownCloud

### ISSUE THREAD

**Issue by thoja21** [owncloud/music#792]
Just updated the Music app via the market in ownCloud 10.5.0 and the app is now broken:

<img width="1355" alt="Screenshot 2020-10-19 at 4 43 02 pm" src="https://user-images.githubusercontent.com/18580089/96473960-298d8900-122a-11eb-906d-7cef6702d908.png">

Owncloud: 10.5.0
Music app: 0.17.0
Server: Ubuntu 18.04 LTS
PHP: 7.2.24
Apache2: 2.4.29

No errors in apache logs, ownCloud, browser console. Uninstalling the app and re-installing it via the Market doesn't fix anything. Not sure what else to try.

**Comment by thoja21** [comment]
Running a check using occ app:check-code music reports the app as not compliant, however the errors/warnings don't look to be the cause of this:

[output.txt](https://github.com/owncloud/music/files/5403119/output.txt)

**Comment by thoja21** [comment]
Just installed a brand new instance of Owncloud 10.5.0 on a VM running the same versions fo Apache, PHP & Ubuntu and added the music app. Same issue occurs on a new install. No errors in the logs.

**Comment by paulijar** [comment]
Thanks for the report. I hadn't noticed this during the development, but now I could reproduce the error (on ownCloud 10.4) when I removed the test version of the Music app and installed it via the Market. After quite a bit of trial and error, I found out that ownCloud actually requires that the application has folders `css` and `js` on its root level. The Music app no longer uses these folders in the version 0.17.0, because with the webpack, it's more natural to store the release versions of both .js and .css files in the `dist` folder. But those folders still need to be there, even if they are empty.

As a quick fix, you could create those folders yourself:
```
cd path_to_your_owncloud_installation
cd apps-external/music
sudo mkdir css
sudo mkdir js
```

I'll also try to publish a new package to the Market very soon.

This problem is specific for ownCloud and does not affect any of the supported versions of Nextcloud.

**Comment by thoja21** [comment]
> 
> 
> Thanks for the report. I hadn't noticed this during the development, but now I could reproduce the error (on ownCloud 10.4) when I removed the test version of the Music app and installed it via the Market. After quite a bit of trial and error, I found out that ownCloud actually requires that the application has folders `css` and `js` on its root level. The Music app no longer uses these folders in the version 0.17.0, because with the webpack, it's more natural to store the release versions of both .js and .css files in the `dist` folder. But those folders still need to be there, even if they are empty.
> 
> As a quick fix, you could create those folders yourself:
> 
> ```
> cd path_to_your_owncloud_installation
> cd apps-external/music
> sudo mkdir css
> sudo mkdir js
> ```
> 
> I'll also try to publish a new package to the Market very soon.
> 
> This problem is specific for ownCloud and does not affect any of the supported versions of Nextcloud.

Great thanks for looking into that so quickly. I can confirm creating those folders sorts this for me. It's a shame nothing was logged in ownCloud for this, or anywhere at all.

**Comment by paulijar** [comment]
Now there is also release v0.17.1 available which adds those two empty folders.
