### ISSUE TITLE
Copying over files from external locations dynamically :

### ISSUE THREAD

**Issue by bmschwa** [owncloud/music#807]
Hello, 

I keep most of my music at aws s3.  Multiple folders ([#760]) would be helpful, but I've noticed that playing from external sources is really sluggish.  The performance would be much better if the entire album could be copied over to the local music folder before, or while, the album starts to play.  That way the local storage could be reserved for things that are playing and an index of external resources available to draw on at the time you want to play some of it.

Thanks,

**Comment by paulijar** [comment]
I guess you are having basically the same problem as discussed in #776. So the problem is that there is always a delay of some (tens of) seconds when changing the playing song, before the music starts playing. What presumably happens behind the scenes, is that first the ownCloud/Nextcloud server loads the whole file from the s3 backend, and only then it starts serving it to the web browser.

Now, if we could start serving the file from your own server before it has been fully downloaded from s3, then it would probably already improve the situation a lot. This might be possible, but I would need to experiment with this a bit before I can say anything definite.

If going with the preloading/caching strategy suggested in the opening post, then I believe that preloading the whole album would be overkill. In most cases, it probably would be sufficient to preload the next upcoming track in the play order while one track is playing. This would also work when playing in some other order than the album order (say, you were shuffle playing over your whole library).

**Comment by bmschwa** [comment]
Thanks much for getting back to me, and for all your work on this project, @paulijar !

**Comment by bmschwa** [comment]
duplicate of #776
