### ISSUE TITLE
Repeat option in Music App doesn't work?

### ISSUE THREAD

**Issue by atkinsom** [owncloud/music#808]
I've been a user of audio player for a little while and found your wonderful app!!! Great app :) I’m trying to use the repeat option in the top right corner of the Music App and no matter what I do it won’t repeat the same song. When selected it just goes to the next song in the list. The shuffle option works fine playing different songs in my entire collection but not the repeat option in my environment below. Any thoughts on making this work? Maybe I’m misunderstanding the option? Thanks very much.

Nextcloud 19.0.5
Music App 0.17.3
Firefox 83 / Chrome / Edge Browsers

**Comment by paulijar** [comment]
Thanks, it makes me feel all warm and fuzzy inside to hear that someone likes the app :D.

The repeat option works but not quite like you expected. What it does is that it repeats the songs of the current "play scope" after all of them have been played once. When you start the playback by clicking a single song in the Albums view, the play scope is set to be the whole library in the album order. Hence, you don't see the repeat button actually do anything before the whole library has been played through. But if you start the playback by clicking an album title, then the play scope will be only that album, and you can see that the same album is repeated over and over again. Similarly, you can click an artist name to set the play scope to be an artist or a genre name in the Genres view to set the scope to be the selected genre. The repeat option works also together with the shuffle option so that each song of the scope will be played once in random order before starting a new round.

Currently, there is no option to directly repeat only a single song because there is no way to set the play scope to be a song. However, you can achieve that by creating a new playlist, and dragging your song to that list. A playlist can be selected as a play scope and it can be repeated also when the list contains just one song.

**Comment by paulijar** [comment]
As a future development idea, it might make sense to turn the repeat button into 3-state toggle: "repeat 1" / "repeat scope" / "no repeat". Then the tooltip could clarify, what is the scope it is currently repeating.

**Comment by atkinsom** [comment]
Thanks very much for the clarification and great suggestion on using a playlist. 👍 The idea of a 3 toggle option sounds good as well as it would fill in all the gaps on what repeat could do. Using the subsonic function with an app I found and it works smooth as butter. Thanks again Cheers.

**Comment by JoshuaPettus** [comment]
The three-state toggle I believe is standard in iTunes and other players, so I don't think you would have to worry too much about your audience.  Though normally when looping a single song, the icon switches to a loop with a little 1 on the bottom right or something.

**Comment by paulijar** [comment]
The three-state repeat button is now included in in the freshly released Music v1.0.0.
