### ISSUE TITLE
music_collection.json file modification date is 5 years in the future

### ISSUE THREAD

**Issue by alexpovel** [owncloud/music#833]
Reopening from nextcloud/server/issues/25855

### Steps to reproduce
1. Install Nextcloud
2. Install and use *Music* Addon
3. In your user's data directory, look at `cache/music_collection.json`: its last file modification date is way in the future.  In my case (dockerized):

    ```bash
    $ NC_USER="dude"
    $ NC_DATA_DIR="/data/nextcloud"
    $ docker exec nextcloud stat "$NC_DATA_DIR"/data/"$NC_USER"/cache/music_collection.json
    File: /data/nextcloud/data/dude/cache/music_collection.json
    Size: 377800          Blocks: 744        IO Block: 4096   regular file
    Device: fe00h/65024d    Inode: 22167419    Links: 1
    Access: (0644/-rw-r--r--)  Uid: (   33/www-data)   Gid: (   33/www-data)
    Access: 2021-03-01 16:29:08.689930601 +0100
    Modify: 2025-11-29 11:53:54.000000000 +0100
    Change: 2020-11-30 11:53:54.851877356 +0100
    Birth: -
     ```

### Expected behaviour

The file should have its actual modified date.

Found this out when trying to set up a script to detect backup success (is the youngest file max. 24h old? -> a backup ran successfully at night). For that, I ran the equivalent of `find "$NC_DATA_DIR" -type f -mmin -1`, which shows the above `music_collection.json` files (multiple times: probably for each user that had set up that app).

### Actual behaviour

File has impossible date/time of last modification.

The culprit must be:

https://github.com/owncloud/music/blob/ab033c58d8cdeebbec1a48c7c725e1dc52118511/lib/Utility/CollectionHelper.php#L96

This would agree with my observations. I installed/first set up the Music addon around 2020-11-29, so the file last modified date is 5 years from then.

### Server configuration

**Operating system:** Docker (`nextcloud:20-fpm`)

**Web server:** `nginx:1-alpine`

**Database:** `mariadb:10.5`

**PHP version:** `7.4.15`

**Nextcloud version:** `20.0.8` (*Music* addon is at `1.0.2`)

**Updated from an older Nextcloud/ownCloud or fresh install:** No

**Where did you install Nextcloud from:** Docker

**Are you using external storage, if yes which one:** local and smb

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

**Comment by paulijar** [comment]
On the line of code you pointed to, we are calling this API from the Nextcloud server: https://docs.nextcloud.com/server/13.0.0/developer_manual/api/OCP/ICache.html#OCP\ICache::set

There, the third parameter is "time to live". We are setting that to 5 years to prevent the server from automatically cleaning up this cached file while it is still valid. If the Nextcloud server has implemented this feature by setting the timestamp of the file to the future, then that's out of our hands.

Maybe 5 years is bit of an exaggeration, but changing that to something like 1 month wouldn't change your issue: if the server implements the time-to-live by setting the timestamp to the future, then setting any non-zero ttl will have the same effect.

The point of caching the music_collection.json for long time is that creating it takes some time (especially on huge libraries) but the same file can be used as long as the music library doesn't change. At least for myself, there are often months if not years between the changes in my music library. Hence, not recreating music_collection.json each time the Music app is opened improves the loading time noticeably. It used to be even more important, like reducing the loading time from some 30 seconds to 3 seocnds, but since then, the logic to create the file has been optimized heavily, and now it saves only a few seconds.

**Comment by alexpovel** [comment]
Okay, thanks for your elaborate explanation. The rationale makes sense, just weird that TTL is set via the file's last modified date, server-side.

As you noted, with this API, *any* TTL greater zero still doesn't solve the problem, no matter how short. I solved it now using `-mmin +0`, so "more than 0 minutes old". This excludes any files from the future.
