### ISSUE TITLE
[Feature Request] sort playlist

### ISSUE THREAD

**Issue by oshyzuka** [owncloud/music#836]
thanks for this great app that I use with Ultrasonic on Android, thanks to your subsonic settings.

It would be great if we could sort a playlist by song name, in ascending or descending order (essentially to prevent songs added twice or more), or completely shuffle the playlist.

**Comment by paulijar** [comment]
I'm closing this as duplicate, because the feature has been requested already once in #689. However, your request didn't go in vain, because I now started to work on the playlist sorting :).

In my opinion, having an option to shuffle the playlist would overlap with our existing shuffle play feature (which shuffles the playback order in which ever context you are playing, not just in playlists). It could make the user experience a bit confusing, if there were two separate features doing essentially the same thing but bit differently.
