### ISSUE TITLE
Error while browsing in some folders

### ISSUE THREAD

**Issue by cdamken** [owncloud/music#839]
ownCloud version 10.6
Music app version: 1.0.2

<img width="444" alt="Screenshot 2021-03-20 at 20 42 40" src="https://user-images.githubusercontent.com/7264495/111883698-48e93780-89bd-11eb-8bc1-b0e74b351abe.png">

I'm getting this error while trying to browse in the folders.

**Comment by paulijar** [comment]
That's nothing to worry about. It just tells that the development tools can't find the map files. The map files are needed to debug the minified source codes bundled in a webpack, but they are of no use for the end user. I don't want to include the map files in the Music app delivery, because right now, the uncompressed size of the whole Music app is around 5 megabytes, but the size of the map files is more than 11 megabytes.

If you actually want to debug the Music app, then you should get the source delivery and build the webpack bundle yourself. This will give you the map files, too.

**Comment by cdamken** [comment]
I notice a problem that jumps to the root folder from the user when trying to go to the parent folder, the only explanation is this, when I disable the music app you can jump between folders without problem:

<img width="484" alt="Screenshot 2021-03-22 at 17 02 02" src="https://user-images.githubusercontent.com/7264495/112020073-5b37b280-8b30-11eb-99b5-8ea9d48e4c1e.png">

**Comment by paulijar** [comment]
Okay, interesting. Does this happen for you on all folders? I couldn't reproduce this on OC10.4. I still need to test 10.6 once I have time.

**Comment by paulijar** [comment]
I now installed OC10.6, pulled Music 1.0.2 from the Marketplace, and tested creating and navigating some nested folders. But still, I could not reproduce the problem. I did see those warnings about missing map files.

**Comment by paulijar** [comment]
Is there anything more you could tell to help me reproduce the issue?

**Comment by cdamken** [comment]
> Okay, interesting. Does this happen for you on all folders? I couldn't reproduce this on OC10.4. I still need to test 10.6 once I have time.

It happens mostly in the folders where I have some music files.

I just downloaded the new version you uploaded in the marketplace. I will provide feedback after testing again.

Thanks

**Comment by cdamken** [comment]
I don't see the problem anymore. If it happens again I will reopen the ticket or create a new one. Thanks for the support!

**Comment by paulijar** [comment]
> I don't see the problem anymore

Okay, great. No related changes have been made on v1.1.0 so I suspect that this has been some kind of installation issue on your previous installation. There used to be a problem which caused all kinds of issues on Files. But that problem was present only in the Music app v0.17.2 and got already fixed by v0.17.3.
