### ISSUE TITLE
Application is not setup via query() but directly at <<closure>>

### ISSUE THREAD

**Issue by adripo** [owncloud/music#849]
Hello,

After enabling debug on Nextcloud 21, I get this error in the logs.

```
[music] Error: RuntimeException: App class OCA\Music\App\Music is not setup via query() but directly at <<closure>>

0. /var/www/html/custom_apps/music/lib/App/Music.php line 73
   OCP\AppFramework\App->__construct("music", [])
1. /var/www/html/custom_apps/music/appinfo/app.php line 19
   OCA\Music\App\Music->__construct()
2. /var/www/html/lib/private/legacy/OC_App.php line 295
   require_once("/var/www/html/c ... p")
3. /var/www/html/lib/private/legacy/OC_App.php line 177
   OC_App::requireAppFile("music")
4. /var/www/html/lib/private/legacy/OC_App.php line 137
   OC_App::loadApp("music")
5. /var/www/html/lib/base.php line 979
   OC_App::loadApps()
6. /var/www/html/index.php line 37
   OC::handleRequest()

GET /apps/logreader/poll?lastReqId=mmKFibsGS2Ok8GHfVH5I
from 192.168.80.2 by adm_ax at 2021-04-22T22:35:55+00:00
```

As I read on [this issue](https://github.com/nextcloud/maps/issues/384) for calendar the solution should be something like [this](https://github.com/nextcloud/calendar/pull/1958/files#diff-079bbe455bfa9aeaf363ae1bc6415ba0R25).

**Comment by paulijar** [comment]
Thanks for the report. Which "logs" do you mean? I couldn't find anything like that from `nextcloud.log` when I tested with NC 21.0.0 and NC 21.0.1 with logging level set to "Debug" (0).

**Comment by adripo** [comment]
Those logs are visible from the interface. Simply go in Settings -> Logs from an admin account.
I enabled debug by adding `'debug' => true,` in config/config.php

**Comment by paulijar** [comment]
Okay, now I got this. The log shown in Settings > Logs is just the `nextcloud.log` file. But there were two reasons, why I didn't see those errors:
1. I didn't have the config `'debug' => true`. What I had tried, was to set the logging level to 'debug' with the config `'loglevel' => 0`. But this is completely different thing and it enables many other logging lines but not this one (which is actually logged on the level `3` i.e. `error`).
2. The block of code checking and printing this error is disabled when running with PHP 7.4 or newer. Looking at the Nextcloud repository history, the check has been disabled there because it didn't work with PHP 7.4, producing false positives for all applications (see https://github.com/nextcloud/server/pull/20749/commits/cba7219b2541c35de574c2a8924a5451a253a8bb).

**Comment by adripo** [comment]
Thanks for the investigation and fix. When will you release the new version?

**Comment by paulijar** [comment]
The new version is probably released later this week.

**Comment by paulijar** [comment]
Music v1.2.0 including this fix is now released.

**Comment by adripo** [comment]
Thank you
