### ISSUE TITLE
Configurable folder view

### ISSUE THREAD

**Issue by groodle** [owncloud/music#869]
I would love to be able to configure how the folder view is displayed. I have my music collection sorted into the following levels of directories:

Music > Artist > Album

I would love to be able to sort see the folder view from the second level i.e. artist, folder level with the albums shown (without tracks) shown under the Artist directory.

Awesome work on this app BTW!

**Comment by raketentimo** [comment]
I would really appreciate this. You cant imagine how many e.g. "CD1" folder I have in the folder View. A configurable value how many parent folder level included in the folder view from a found audio file would be helpfull. And since spotify I have so many CDs to rip I do not know the artist for a album anymore.

AND (going wild) a filter which triggers the inclusion of one more parent folder like /CD\s?\d|Disk\s?\d/


e.g: With 2 parent Levels:
```
AwsomeArtist
       Album1
            Track1
            Track2
            :
            ;
      New Album
            Track1
            Track2
            :
            ;
OldArtist
      GoldBuyMeAgainAlbum
            CD1 #<-- matches "CD\d"
                Track1
                Track2
                :
                ;
            CD2
                Track1
                Track2
                :
                ;
       Album1
            Track1
            Track2
            :
            ;
Various Artist
      Kontor 2021.01
            Track1
            Track2
            :
            ;
      
  
     
```

**Comment by paulijar** [comment]
I'm a bit reluctant to add new configuration options when not absolutely necessary. But if the "hierarchical folders view" (https://github.com/owncloud/music/issues/742) was implemented, would that solve all the underlying issues presented here?

**Comment by raketentimo** [comment]
I dont want to hijack this enhancement issue too much but in my opinion this enhancement would by "eye candy" on top of #742.  

I also found an issue with my idea: I have several albums as flac AND mp3. mp3 from Amazon Auto-Rip to get the cover arts and flac from ripping the CD for Mixxx DJ stuff ...  Making the enhancement more complicated.

The current folder view has the advantage of being theoretically much better usable with mobile/touch devices. My Idea was not to collapse the folder view - just add more information to the "Folder Name".. And perhaps this will help with ampache/subsonic clients too.

However #742 is much more pressing since this is the only solution that will always work.

**Comment by paulijar** [comment]
IMHO, the hierarchical folders view introduced in v1.4.0 already fills the gap which would be targeted by this feature request. Regarding the adding of more info to the folder name, note that the full path of each folder is already visible in the tooltip when hovering over the folder name, both in the hierarchical layout and in the traditional flat layout. Also, the full path may be targeted with the search feature of the Music app on both layouts of the Folders view.

For these reasons, I'm closing this issue now.
