### ISSUE TITLE
Subfire Chrome app always says "HOST NOT FOUND OR CONNECTION REFUSED"

### ISSUE THREAD

**Issue by etyrnal** [owncloud/music#879]
Subfire Chrome app always says "HOST NOT FOUND OR CONNECTION REFUSED"

This is on a working instance of nextcloud using the recommended url and a generated app password.

HOST: http://<redacted>:<redacted>/index.php/apps/music/subsonic
USERNAME: <working redacted username>
PASSWORD:  <generated app password>

Is this functionality not working?

**Comment by paulijar** [comment]
It seems that the SubFire player supports only the "token-based" authentication of the Subsonic API. This is not supported by the Music app. The thing is, the token based authentication is intended to improve the security but because of its poor design, it can be argued that it is actually *less* secure than the password based authentication. That's why I don't want to support it in the Music app. In majority of the Subsonic clients, the token-based authentication can be disabled in favor of the password-based but I didn't find such setting from SubFire.

**Comment by etyrnal** [comment]
thank you!
