### ISSUE TITLE
Non-ASCII characters and Encoding Issue

### ISSUE THREAD

**Issue by wonderfulShrineMaidenOfParadise** [owncloud/music#882]
**Describe the bug**

**To Reproduce**
1. Add any music with non-ascii charcters. For example, ``永夜抄　～ Eastern Night.``.
2. See the library. There is a theme ``ié´@` Eastern Night.``.

**Expected behavior**
There should be a theme shown as ``永夜抄　～ Eastern Night.``

**Screenshots**
![Screenshot_20210824_040835](https://user-images.githubusercontent.com/86928419/130503881-11f2e6eb-4452-402f-a4f3-f928731dbf9d.png)

**Server (please complete the following information):**
 - Nextcloud version: 21.1.0.1
 - Music app version: 1.2.1

**Comment by paulijar** [comment]
Hi. The application should be able to handle any UTF-8 data as demonstrated by the following screen shot from my test library. Are you sure that your file is actually using UTF-8 encoding on its metadata? If you can share a sample of such a problematic file, I can take a look. You can find my email address from my github profile.

![image](https://user-images.githubusercontent.com/8565946/130508627-ed429c76-b046-42fe-a877-c16ca49d910c.png)

**Comment by wonderfulShrineMaidenOfParadise** [comment]
Okay. I have mailed you with the theme ``永夜抄　～ Eastern Night..wav`` attached.

**Comment by paulijar** [comment]
The new Music v1.3.2 release now contains a fixed version of the getID3 library where WAV files with non-Latin characters work better. Files like in the opening post (*) still cannot be supported, because that is basically not possible by following the standards. However, the WAV files containing ID3v2 tags should now be shown correctly with any Unicode content. The ID3v2 tags may be written, for example, with the [Mp3tag](https://www.mp3tag.de/en/index.html) application.

(*) File with metadata stored in the RIFF headers using some encoding other than ISO8859-1
