### ISSUE TITLE
Upgrade to Music v.1.3.1 breaks Subsonic for play:Sub

### ISSUE THREAD

**Issue by frake65** [owncloud/music#886]
After Upgrade to 1.3.1 the login process for App play:Sub (IOS) no longer works. 
Failure message says "wrong username / password" even with newly generated credentials.

**Comment by paulijar** [comment]
Thanks for the report. Can you find anything relevant from owncloud.log or nextcloud.log? If you are going to post any Subsonic-related log lines here, then note that those contain your API key in plain text or in trivially coded format. Those lines look something like `{"reqId":"preIfRsYyyUHV3QShaFs","level":0,"time":"2021-08-31T21:11:06+03:00","remoteAddr":"91.157.45.128","user":"--","app":"music","method":"GET","url":"\/nextcloud\/index.php\/apps\/music\/subsonic\/rest\/getIndexes.view?u=pauli&p=1234567890abcdef&v=1.2.0&c=DSub","message":"Subsonic request getIndexes.view","userAgent":"DSub","version":"17.0.10.1"}`
There, the part following the `&p=` and ending to the next `&` is your API key which should be hidden from public posts.

**Comment by frake65** [comment]
Hi,
I am not sure if this is what you are looking for, but I got this message:
{"reqId":"iqDDCRcsjL1T6e5cX47L","level":0,"time":"2021-09-01T16:32:10+00:00","remoteAddr":"95.112.239.44","user":"--","app":"music","method":"POST","url":"/apps/music/subsonic/rest/ping.view","message":"Token-based authentication not supported","userAgent":"playSub/2021.2 (iPhone; iOS 14.7.1; Scale/3.00)","version":"22.1.1.2"}

**Comment by paulijar** [comment]
Yes, the first message is relevant. Your client seems to be using HTTP POST instead of HTTP GET, so you don't need to worry about the API key hiding thing I mentioned above; with POST, the API key and other arguments are not visible in the logs.

This message confirms what I was suspecting: your client now tries to use the "token-based" authentication of the Subsonic API instead of the "password-based". This is probably related to the fact that the Music app has incremented its Subsonic API version to 1.13.0, and with a "real" Subsonic server, this would mean that the token-based authentication would be available. However, the Music app does not support it. The reason for this is that, although the token-based authentication is intended to improve the security, the API design has been screwed up and the new system is arguably less secure than the original password-based one. This is because the token-based system would enforce the server to store all the passwords/API-keys in plain text.

On the other hand, even the "real" Subsonic server cannot use the token-based system on all configurations: If Subsonic server has been set up to use LDAP authentication server, then it doesn't know the plain text passwords either, and cannot use the token-based system. Hence, a good client should always offer the possibility to not use the token-based authentication.

So first you should look through the settings of your client. If you can find anything related to the authentication type, then ensure that token-based authentication is disabled or password-based enabled. Or if you can find some setting called e.g. "LDAP support", then ensure that it is enabled. If none of these are found, then submit a feature request for the play:Sub client.

PS. The deprecation notice you saw is a known issue. Nextcloud would want the apps to move on to their new "bootsrapping" system, but that would be problematic for the Music app since the new system does not work on ownCloud (or the oldest supported versions of Nextcloud). Hence, we would need to branch the application to use two different systems, depending on the host cloud. This would increase the maintenance effort and I don't want to do it until absolutely necessary. But I'm afraid that the day may come when the support for the deprecated system is dropped completely from NC.

**Comment by frake65** [comment]
Thank you very much for your research and differnciated answer. 
In fact there is a switch for disabling token authentication available within play:sub.
I will give an update if that works for me - but I'm quite positive       about the outcome :)
Great work!

**Comment by paulijar** [comment]
Great, case closed!
