### ISSUE TITLE
Suddenly get "Connection failure: Authentication by token is not supported for LDAP users" error with Subsonic

### ISSUE THREAD

**Issue by on3iro** [owncloud/music#893]
I just upgraded to the newest version of the music app and suddenly get the aforementioned error whenever I try to connect to the server from the Ultrasonic Android app.

Nextcloud-Version: 21.0.3
Music: 1.3.3

None of my users is an LDAP user however.

Any idea what could cause this and what I could do to fix this?

Thanks in advance!

**Comment by paulijar** [comment]
In the Ultrasonic server settings, you need to enable the option "Force plain password authentication". The Music app doesn't support the "token authentication". The real Subsonic server supports it starting from the API version 1.13.0 *unless* the LDAP authentication is used. If the client tries to use the token authentication with the Music app, the Music app responds with the same error code as is used by the real Subsonic server + LDAP combo.

This probably hasn't been a problem for you before because the Music app has been using older API version up until the Music v1.3.0. I assume that Ultrasonic has been smart enough to disable the token authentication in that case regardless of the setting.

**Comment by on3iro** [comment]
@paulijar works like a charm! Thanks a lot for the quick answer 👍
