### ISSUE TITLE
Indexing music in subfolders

### ISSUE THREAD

**Issue by atkulp** [owncloud/music#901]
I have a top-level Music folder containing a few hundred folders per artist, then additional level for albums.  It seems that it won't scan sub-folders based on me trying to add various levels.  Is there a flag somewhere?  Any reason it's not the default behavior?  Any help would be appreciated!

**Comment by paulijar** [comment]
Any folder structure should not be a problem for the Music app per se. But are your files maybe on some external storage? Or have you modified the folder structure directly through the OS file system? In both of these cases, the internal book keeping of ownCloud/Nextcloud may be out-of-date with the actual file system. The Music app can find only those files which are indexed by the cloud. If such "out-of-sync" is the root cause, then using the command `occ files:scan` might help. Look at the help of the command for finer details.

**Comment by atkulp** [comment]
I didn't realize it hadn't indexed the external folder.  thanks for your help.  all is good now!
