### ISSUE TITLE
[Subsonic] getArtistInfo doesn't work with song id

### ISSUE THREAD

**Issue by wiz78** [owncloud/music#906]
Subsonic API docs specify that getArtistInfo can be called with "The artist, album or song ID.", but the Music app only handles the first two cases.

**Comment by dslengel** [comment]
Please let me now!
Thanks

**Comment by paulijar** [comment]
Okay, thanks for the info. I don't have any Apple devices to test with so that explains why I haven't seen any problem.

> It can't pass the artist ID since Subsonic doesn't provide it for tracks.

Are you sure about that? At least the Subsonic demo server seems to include the property `artistId` on the `child` entries as can be seen e.g. in http://demo.subsonic.org/rest/getMusicDirectory.view?u=guest4&c=test&v=1.16&s=123&t=fcf41657f02f88137a1bcf068a32c0a3&f=xml&id=260

It should be noted, though, that this `artistId` cannot be passed to `getArtistInfo`, it works only with `getArtistInfo2`. According to http://www.subsonic.org/pages/inc/api/schema/subsonic-rest-api-1.16.1.xsd, this property has been added by the API v1.8.0 while `getArtistInfo` and `getArtistInfo2` are not available before API v1.11.0.

**Comment by paulijar** [comment]
Okay, I see. The Subsonic API can be a bit awkward to use with its ID3/filetree duality. And the Music app's implementation of the API is yet another story because of the different starting point and somewhat different design philosophy.

But anyways, I have now made a fix for this. So when the next Music app release rolls out probably withing a couple of weeks, the `getArtistInfo` should work fine also with track and album IDs.

Thanks for reporting the issue!

**Comment by paulijar** [comment]
Music v1.4.1 is now out, including also this fix/enhancement.

**Comment by erwinlagu** [comment]
is this already fixed?

**Comment by paulijar** [comment]
@erwinlagu Yes, as stated above: https://github.com/owncloud/music/issues/906#issuecomment-955746778
