### ISSUE TITLE
Ampache5 API 

### ISSUE THREAD

**Issue by memen45** [owncloud/music#909]
Just wanted to notify that Ampache has released a new API version, [Ampache5](https://ampache.org/api/api-json-methods). I was wondering if you were planning to implement the changes in the near future as well!

**Comment by lachlan-00** [comment]
I'm almost done importing the old API's will update more tommorow.

TLDR is
* send your version number (440000, 5.1.1, 3900001, etc)
* I then record your session data based on major revision (3,4,5) 
* return data/perform actions using that version of the api

**Comment by lachlan-00** [comment]
support added now in https://github.com/ampache/ampache/commit/098518e51f4f646001df817b2b7c7758c35252f9

https://develop.ampache.dev has been updated so you can try it out there.

**Comment by memen45** [comment]
@paulijar any update on this? As you mentioned, especially the bookmarks are new in the Ampache5 api, which might make it worth implementing it.

**Comment by paulijar** [comment]
@memen45 Nope, sorry, not much has happened in this project during this year.

**Comment by paulijar** [comment]
In July, I should again have time to do some development for this project. I'll try to add some level of support for Ampache 5 API during this development sprint.

**Comment by lachlan-00** [comment]
The change between api 5/6 is minimal. (A fully supported API6 server should be fully compatible with Ampache5)  I'm making sure that they're as fully backwards compatible as possible.

Previews are up https://github.com/ampache/ampache/releases/tag/6.0.0-preview1

Added/Changed things in API6 compared to 5.

* JSON responses
  * Cast bool fields to true and false instead of "1" & "0"
  * Add total_count to responses to give clients an idea of the total possible objects
* XML responses
  * Api6 XML success and error response messages are put in a message element (like json)
  * For data responses id is the only attribute and everything else is an element
  * Name was not set as an attribute OR an element so now it's always an element
  * Return original XML output (that may be malformed) when loadxml fails.
* Renamed user_update to user_edit (user_update still works and will be depreciated in API7)
* Albums with no album_artist may now return 0 artist called 'Various'
* Api6::get_indexes: This method is depreciated and will be removed in Ampache 7.0.0 (Use Api6::list instead)

Removed things in API6

* preciserating removed from all objects (use rating)
* Remove non-song MBIDs as not relevant to the object (very unlikely it was used)
* album_songs remove exact as a parameter
* stream remove podcast as a valid type value (it was meant to be podcast_episode)

**Comment by lachlan-00** [comment]
I forget if i mentioned this before but another option is to make sure you send a api4 version in your strings.

For example sending `http://localhost/ampache/server/xml.server.php?action=handshake&auth=PASSPHRASE&timestamp=TIME&version=440001&user=USER`

will tell the server that you're using api4 and will send data/responses in the api4 format

After Ampache 5.2 you can send any supported version from api3+ and get the latest supported version of that major release.

**Comment by paulijar** [comment]
I created a WIP pull request https://github.com/owncloud/music/pull/1078 to follow progress on this topic.

**Comment by paulijar** [comment]
Music v1.9.1 with support for API versions 3-6 is now finally out. The new version covers quite large portion of the APIv6 specification, including almost all methods which are applicable on this app. Feel free to open a new issue if something important is still missing or something is not working as expected.
