### ISSUE TITLE
Music App Adding Talk Voice Messages as music

### ISSUE THREAD

**Issue by blackangelpr** [owncloud/music#925]
Voice messages from talk app are showing under the Music app location any possibility to eliminate the scan on the talk app folder? or make it to the music folders only? 

best regards
![music app ](https://user-images.githubusercontent.com/10284346/143969315-73ee9fdc-cc7d-4eaf-a5e1-e707ce033e9c.jpg)

**Comment by paulijar** [comment]
From the Settings view of the Music app, you can set the base path of your music library and/or excluded paths so that the folder of the Talk app is not included.
![image](https://user-images.githubusercontent.com/8565946/144015272-f5579260-a221-4007-82c5-2cd8ea6f0392.png)

It should be noted, that the changes on the *excluded paths* take effect only upon rescanning the library (but changes on the base path take effect immediately). From the web UI, the rescanning requires erasing the library first. But with the command line `occ` utility, you may use the more subtle option `occ music:scan --clean-obsolete` to remove just the excluded folders without rescanning everything else.

**Comment by paulijar** [comment]
I assume that the instructions above solved the issue, and this may be closed now.
