### ISSUE TITLE
Requested action getScanStatus is not supported when trying to login via sonixd

### ISSUE THREAD

**Issue by fuomag9** [owncloud/music#926]
As per the title, it's not possibile to use sonixd at the moment due to the following error on login `Requested action getScanStatus is not supported`. See screenshow below:

![image](https://user-images.githubusercontent.com/1580624/145793899-ece991fa-9a3f-47fc-aff0-64c53396763e.png)

**Comment by paulijar** [comment]
Thanks for the report. The Subsonic API methods related to library scanning are not implemented, largely because I have never seen a client which would want to use those. But this is the first time I hear about Sonixd. I shall add at least stub implementations for the needed API methods and try to test the compatibility with this client also otherwise.

**Comment by paulijar** [comment]
I now added a stub implementation for the Subsonic method `getScanStatus` and could get past the login phase with the sonixd client. Unfortunately, I still couldn't make the app work on my system. The problem was that the client entered an infinite redirection loop, and most of its requests never reached the Music app. I believe that the root cause for this is somewhere in my ngingx configuration but I haven't figured it out. There's a good chance that most other people will not suffer from the same problem. I have previously seen the same problem on another HTML5 Subsonic client Jamstash, and I couldn't figure it out that time, either.

In case anyone wants to patch their Music app installation to test the sonixd client before the next Music app release (which is not scheduled yet), the code change needed is very small. You can find the details from the commit linked above.

**Comment by paulijar** [comment]
If @fuomag9 or anyone else tests this with an unofficial version, I would be interested to hear about the results.

**Comment by paulijar** [comment]
The stub for getScanStatus is now included in the new Music release v1.5.1. Please open new issues in case you still face any problems on sonixd.

**Comment by fuomag9** [comment]
Hey @paulijar sorry for the late response! Login with sonixd works now and the client seems to have no issues in detecting playlists or playing music. Very much thanks!!
