### ISSUE TITLE
No music found from group folder

### ISSUE THREAD

**Issue by intervisionlord** [owncloud/music#933]
I have installed app and set path to my mp3s are located but tehere are no files in app. I have already tried to reset collection but it was not helped.

**Comment by paulijar** [comment]
Are your mp3 files maybe located on some external storage? If yes, then your case might be similar to https://github.com/owncloud/music/issues/931.

If not, then can you find anything relevant from the owncloud.log or nextcloud.log file?

**Comment by intervisionlord** [comment]
> Are your mp3 files maybe located on some external storage? If yes, then your case might be similar to #931.
> 
> If not, then can you find anything relevant from the owncloud.log or nextcloud.log file?

No there are not on external storage, but in group directory. Maybe this is a reason of this behavior, because when i move them to other non group directory this problem disapeared.

**Comment by paulijar** [comment]
Okay, there has been a previous report https://github.com/owncloud/music/issues/844 about similar issue with group folders. However, I haven't been able to reproduce the problem. So the actual root cause is currently a total mystery, and as long as I can't reproduce it, it's basically impossible to investigate it.

**Comment by intervisionlord** [comment]
Yesterday a new update for Group Folders app was released. I have tested described behavior again and seems it works now.
So, i suppose, i should close this issue.
