### ISSUE TITLE
Administrator settings

### ISSUE THREAD

**Issue by ghost** [owncloud/music#936]
So that the administrator can specify predefined radio stations, albums and podcasts for the entire Nextcloud instance.

**Comment by ei8fdb** [comment]
@R7JANV1 can you give some more information about what you mean?

**Comment by R7JANV1** [comment]
self-explanatory right?

**Comment by ei8fdb** [comment]
> self-explanatory right?

Clearly it wasn't. Otherwise I wouldn't have asked.

**Comment by R7JANV1** [comment]
so e.g.  a radio station is displayed as a radio for each user and does not have to be added by yourself

**Comment by paulijar** [comment]
For the radio stations, something similar has been requested before in https://github.com/owncloud/music/issues/860. 

For the albums, you could achieve something like this by using the Group folders add-on of Nextcloud, placing the albums to be added to each user to the group folder. But because of the nature of how the Music app has been designed, each user still needs to scan those shared files separately.

Also, you could place an exported list of radio stations in the group folder. That way, each user would just need to import this list of stations. And if https://github.com/owncloud/music/issues/904 ever gets implemented, then you could do the same with the podcasts.

**Comment by R7JANV1** [comment]
I think a simple menu in the administrator menu would be more helpful.

**Comment by paulijar** [comment]
Closing as not planned. The scope of the request is  too wide for comfort, and I don't believe that the number of users using such feature would justify the amount of work needed. And on the other hand, this is partially covered by other open requests. Also, the original requestor has become a ghost since filing this.
