### ISSUE TITLE
Nextcloud 23.0.3 - appinfo/database.xml file is not longer supported

### ISSUE THREAD

**Issue by str0g** [owncloud/music#969]
When I try to enable I got this message The appinfo/database.xml file is not longer supported.
What am I doing wrong?

**Comment by paulijar** [comment]
How are you installing the Music app, and which version of the app is that? Defining the database content using database.xml is something which has not been supported by Nextcloud since NC22. On the other hand, this is the only method supported on ownCloud. Hence, we have had mutually incompatible installation packages for Nextcloud and ownCloud since Music v1.2.1.

My best guess about your situation is that you have first installed some Music app version older than v1.2.1 on some older NC version, and since then, you have updated to NC23. To proceed, you would need to update also the Music app to its latest version. If this doesn't work directly from the NC app installer, then you might need to manually destroy all the Music app files from the Nextcloud installation folder.

**Comment by str0g** [comment]
Thanks this is the case.
