### ISSUE TITLE
Owncloud Unknown Artist

### ISSUE THREAD

**Issue by Pecadis** [owncloud/music#97]
Hi kabum,

i have a problem with the Mp3. I've uploaded some Mp3's but the app doesn't get the Mp3 Tags and just let me see that all of them are "Owncloud unknown artist" or "Owncloud unknown artist". I have seen that i have the same problem with the internal Media App and found a soloution here (https://github.com/owncloud/apps/issues/1056)

May you tell me how to fix the problem?

Thank You
Pecadis

![unbenannt](https://f.cloud.github.com/assets/5543829/1212434/75e1a03a-2618-11e3-9b07-13b7e1e2283c.png)

**Comment by michaelkrtikos** [comment]
It seems that i am facing the same issue with all the tracks marked as unkown artist...

I have tried the trick with emptying the tables of the database after changing the value to false in option_max_2gb_check and it didnt work...

I am running the app from owncloud 8.0.2 on XAMPP server on Windows 8.1 64bit

Could you please guide me for further actions?

Thank you very much

**Comment by xn--nding-jua** [comment]
Hi michaelkrtikos,

the problem has been specified by one of the users: if you are using the encryption-app, the music-app can't open the encrypted file and fails to read the ID3-Tag. There are two workarounds:

1. using the path two posts above this one (add the code-lines after line 200 in the file  "/owncloud/apps/music/utility/scanner.php"

or

2. add some code to the music-app-scanner, so that the mp3-file will be first deencrypted to a temporary folder, than scanned and deleted afterwards

kind regards

**Comment by michaelkrtikos** [comment]
Hello... I will try the first code bur i am not using any encryption app thats why i didnt try it until now...

Will report back...

**Comment by michaelkrtikos** [comment]
Good morning everyone...

I confirm that the above works...

Thank you very much...

**Comment by paulijar** [comment]
I believe that any (possibly) remaining metadata extraction problems are covered by #153 and #463, and this very old issue can be closed.
