### ISSUE TITLE
question about @__thumb

### ISSUE THREAD

**Issue by mybuntu-git2** [owncloud/music#976]
hi,
I'm on a qnap where we have @recycle and similar stuff that needs to be in the blacklist to not mess with "real" data.
I noticed when doing the scan via CLI, the app scans also /@__thumb/ subdirector(ies). is that part of the music app data model? or we should blacklist these as well?
if it is part of the data model is it normal that running scan I see in the console "scanning /mysong.mp3" and then "scanning /@__thumb/mysong.mp3" ? 

running 1.5.1

**Comment by paulijar** [comment]
The Music app doesn't create any files or folders into the user home folder; all the internal bookkeeping of the app is stored in the database. So the folder @__thumb and its contents must have been created by some other party. If those files are not a desirable part of your music collection, then you should set the root path of your collection and/or the excluded paths so that those folders are left out. Both of these options can be found from the Settings view of the Music app.

**Comment by paulijar** [comment]
Apparently no issue on the Music app => closing
