### ISSUE TITLE
Music doesn't recognize files larger than 10 MB

### ISSUE THREAD

**Issue by niklasschbdst** [owncloud/music#991]
whether it's in files or in the app itself, files larger than 10 MB are not playable.

**Comment by paulijar** [comment]
That's weird. Can you download the same file from the Files app?

**Comment by niklasschbdst** [comment]
Yes, I can download the files. Also the symbol doesn't change to the Music symbol. It is still the usual files symbol.
I'm on Nextcloud 22.2.8 and Music is 1.5.2, if that helps

**Comment by paulijar** [comment]
The symbol in Files depends on the mime type detected for the file which on the other hand depends on the file extension. What is the file type of those problem files?

**Comment by paulijar** [comment]
I feel like some piece of the puzzle is missing; none of this makes much sense to me.

Did I understand it correctly that you do see those problem files in the Music app but they just don't play? Can you find anything from nextcloud.log after the failed attempt to play a song from the app?

**Comment by niklasschbdst** [comment]
No, I'm sorry for the confusion. The music app does not find the large files. But I only want to use the music app to play files in the files app. And in the files app the symbol of the large files don't change und the files are not playable.

**Comment by paulijar** [comment]
Well, that makes a bit more sense, because at least the behavior is consistent: showing the "audio" file type icon in Files and being able to play the file in Files and the Music app showing the file all require that the mime type detected by Nextcloud for the file is of format `audio/*`. But as far as I know, the mime type detection should be based solely on the file extension. It beats me, how the file size could have any effect on this. 

Just to make sure, you have some smaller audio files with exactly the same file extension as those >10 MB files and those smaller files are detected to be audio files without any problems?

**Comment by niklasschbdst** [comment]
Yep

**Comment by niklasschbdst** [comment]
I tried deinstalling the music app. And I don't think my problem is a problem of the music app, its the nextcloud which doesn't detect my files as music.

**Comment by paulijar** [comment]
Yes, that's what I would have assumed. It's up to Nextcloud to identify the file types and the Music app just registers handlers for the files of type `audio/*`. Have you tried reporting this to https://github.com/nextcloud/server/issues?

**Comment by niklasschbdst** [comment]
I will. Thank you for your time and your kind support!
