### ISSUE TITLE
Problems with Music and LastFM API

### ISSUE THREAD

**Issue by SGSMediaGroup** [owncloud/music#995]
Can someone help me?
In Nextcloud, when I add LastFM's API to the config to show details of my songs, I always get the error "Unable to connect to LastFM.
The following error message appears in the Nextcloud log

Error: file_get_contents(http://ws.audioscrobbler.com/2.0/?method=album.getInfo&amp;artist=Dj+Robin+x+Schurze&amp;api_key=*************** *******&amp;format=json): Failed to open stream: HTTP request failed! HTTP/1.1 400 Bad Request at /apps/music/lib/Utility/LastfmService.php#224

Can anyone help me make it work??

**Comment by paulijar** [comment]
What kind of album information do you expect to find from Last.fm when the album is unknown?

**Comment by SGSMediaGroup** [comment]
That I can see the album the song belongs to, or the details of the song
if it can't show an album. 

Am 19.07.2022 10:29, schrieb Pauli Järvinen:

> What kind of album information do you expect to find from Last.fm when the album is unknown? 
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
> You are receiving this because you authored the thread.Message ID: ***@***.***>

 

Links:
------
[1] https://github.com/owncloud/music/issues/995#issuecomment-1188757389
[2]

**Comment by paulijar** [comment]
Looking at album info for an 'Unknown album' from Last.fm makes conceptually no sense because, for all we know, each track shown under that album could actually come from different album. The best you can do is to view the track details and open the Last.fm tab:
![image](https://user-images.githubusercontent.com/8565946/179719706-1ecc195c-6017-4b9a-9cd1-8f6230f727e1.png)
There, click the "Read more on Last.fm" link and you may find information about the album on the Last.fm site.

Now thinking about it, it would be a viable idea for future development to add the album name and link found from Last.fm on this tab of the track details.

**Comment by paulijar** [comment]
The newly released Music v1.6.0 now has two related enhancements: The app no longer tries to fetch info from Last.fm for the "Unknown album", and the Last.fm tab of the track now shows also the artist and album names retrieved from Last.fm (if available).
